(function(f){function F(a){"$ignore"===a&&(e.define=w,w=null)}function G(a,b,c){c||(c=b,b=[]);h=0;z[a]=!0;p(b,function(){m[a]=c.apply(null,arguments)})}function p(){n.push(arguments);A()}function A(){var a,b,c,d,k,e,f,g;if(n.length){a=n;n=[];e={};l=[];for(b=a.length;b--;){d=[];f=!0;for(c=a[b][0].length;c--;)k=a[b][0][c],k in m?d[c]=m[k]:(e[k]||z[k]||(l.push(k),e[k]=!0),f&&(n.push(a[b]),f=!1));if(f){g=!0;try{a[b][1].apply(null,d)}catch(h){q(h,"runtime")}}}g?A():n.length&&!r&&(r=x(B,100))}}function B(){var a,
b,c,d,e=[];r=C(r);if(!h){y=C(y);for(a=l.length;a--;)d=l[a],t[d]?(l.splice(a,1),2>t[d]&&(t[d]++,e.push(d))):t[d]=1;h=l.length;e.length&&q(Error("Modules '"+e.join("', '")+"' failed to load"),"loadFailed");if(h){y=x(H,6E4);try{b=g.createElement("script"),b.src=I+"//s1.adform.net/stoat/619/s1.adform.net/load/v/0.0.176/e/"+m.$env.$hash()+"/i/"+m.$ignore+"/r:"+l.sort().join(":"),c=g.__gEBTN__("script")[0],b.onerror=J,c?c.parentNode.insertBefore(b,c):(g.body||g.head).appendChild(b)}catch(f){q(f,"script_insert")}}}}function J(){u("response_error",
this.src)}function H(){h=0;B()}function u(a,b,c){var d=[],e=f.Image;Math.random()<(c||.03)&&(d.push((v&&v.host||"//track.adform.net")+"/jslog/"),d.push("?src="),d.push(encodeURIComponent(a)),d.push("&msg="),d.push(encodeURIComponent(b)),a=e?new e(1,1):g.createElement("img"),a.src=d.join(""))}function q(a,b){var c=""+(a.stack||a);0>c.indexOf(a.message||"")&&(c=a+"\n"+c);x(function(){throw c;},0);u(b,c)}function D(){for(var a=arguments,b=0,c=a.length,d=[];b<c;b++)K(a[b])||d.push(a[b]);return d.length?
E.apply(e,d):e.length}function K(a){function b(b){b.apply(null,a.slice(1))}var c=a[0],d=m[c];d?b(d):p([c],b)}var w,E,r,y,l,e=f._adfq||(f._adfq=[]),g=f.document,x=f.setTimeout,C=f.clearTimeout,v=f.Adform,I=v&&"https:"===(v.shost||"").split("/")[0]||"https:"===f.location.protocol?"https:":"http:",m={require:p,$boot:{window:f,require:p,rethrow:q,log:u,deprecate:function(a,b,c){var d=!1;return function(){d||(u("deprecate",b,c),d=!0);return a.apply(this,arguments)}}}},h=0,n=[],z={},t={};g.__gEBTN__=g.getElementsByTagName;
(function(){var a;e.define?(w=e.define,e.define=F):(E=e.push,e.define=G,e.push=D,a=e.slice(),e.length=0,D.apply(e,a))})()})(window);
(function(a,h,c,b,e,N,L,M,O,P,G,I,J,w,y,u,K,H,d){
a(h,[c],function(c){c=c.window;var a=c.Adform||{},d=a.ET||{},b=a.RMB||{},e=b.Content||{};b.Type=b.Type||{};b.Content=e;a.ET=d;a.RMB=b;return c.Adform=a});
a(b,[c],function(fa){function M(f){return f}function N(){function f(){for(var u=1,d=t;u<g.length&&!g[u];u++)d=d.parent;try{return d==d.Function("return window")()}catch(a){}}function v(u,d){var a=d.charAt(0).toUpperCase()+d.slice(1);return h(u,d,"ms"+a,"moz"+a,"webkit"+a)}function h(a){for(var d=arguments,b=d.length;--b;)if(d[b]in a)return d[b]}function c(a,d){return 0<=(""+a).toLowerCase().indexOf(d.toLowerCase())}var a=fa.window,e=a.document,w=e.documentElement,k=a.navigator,t=a.parent,
l=k.vendor,b=k.userAgent,x=e.createElement("div"),g=function(a){for(var d,b=100,c=a.top,e=[!0];--b&&a&&a!=c&&a!=a.parent;){try{d=!!(a=a.parent).Image}catch(f){d=!1}e.push(d)}return e}(a),p=a!=t,O=!p||g[1],q=!p||g[g.length-1],P=p&&f(),L=function(){var b,d=k.plugins,c=k.mimeTypes,e=a.ActiveXObject,f=26,d=d&&d["Shockwave Flash"]&&(!c||!c["application/x-shockwave-flash"]||c["application/x-shockwave-flash"].enabledPlugin)&&(d["Shockwave Flash"].version||d["Shockwave Flash"].description)||"";if(!d&&e)for(;6<=
f--;)try{b=new e("ShockwaveFlash.ShockwaveFlash."+f);6==f&&(b.AllowScriptAccess="always",d="WIN 6.0.21.0");try{d=b.GetVariable("$version").replace(/,/g,".")}catch(g){}break}catch(g){}return parseFloat(d.replace(/^.*?(\d+[\.,].*$)/,"$1").replace(/(^\d+\.)|\./g,"$1"))||0}(),ga=v(e,"hidden"),B=!!ga,y=/MSIE|Trident/i.test(b),ha=y&&("Microsoft Internet Explorer"===k.appName&&/MSIE (\d+[\.\d]*)/i.exec(b)||/rv:(\d+[\.\d]*)/i.exec(b))?parseFloat(RegExp.$1):-1,x=h(x,"addEventListener"),Q=c(b,"Macintosh"),
z=c(l,"apple computer"),C=c(b,"ipad"),D=c(b,"iphone"),m=C||D,n;n=m&&(n=/\sos\s(\d+)_\d+/i.exec(b))&&(n=4<n[1]>>0);var E=c(l,"google"),F=!m&&c(b,"android"),R="ontouchstart"in e||"ontouchstart"in a,G=(z||E)&&/(chrome|crios)+\/[\d\.]+\s/i.test(b),M=G&&/[chrome|crios]+\/([\d\.]+)\s/i.exec(b)[1],H=/Firefox\/[\d\.]+/i.test(b),S=c(b,"opera"),l=c(b,"opr")&&c(l,"opera software"),r=!/Chrome|CriOS|Skyfire/i.test(b)&&/Safari+\/[\.\d]+$/i.test(b)&&z,b=y&&(c(b,"IEMobile")||c(b,"WPDesktop")),T=r&&!("webkitRequestAnimationFrame"in
a),U="screenX"in a,V="outerWidth"in a,W="mozInnerScreenX"in a,w=w.msContentZoomFactor,X=!(!e.fireEvent||!e.attachEvent),N=v(a,"requestAnimationFrame"),Y=m&&!r&&!k.standalone,Z=h(a,"IntersectionObserver")&&!H,I=m||F,e=B&&!I&&!b&&q&&h(e,"hasFocus"),aa=!q&&11==ha,J,ba,A=a.wisp,ia=A&&A.sdk&&A.sdk.platform,ca=r&&!q,ja=a._adform&&a._adform.tagFrame,da=!!ja,ka=function(a){for(var b=g.length,c,e=0;e<b;e++)g[e]&&(c=a.mraid||c),a=a.parent;return c}(a),K=!!ka,ea=k.sendBeacon&&!K;if("android"==ia||"ios"==ia)for(var la in A)if(/^adObject.+/i.test(la)){ba=
A[la].inscreen;J=!!ba;break}return{result:[p,O,q,P,B,y,x,Q,z,C,D,m,n,E,F,R,G,H,S,l,r,b,T,U,V,W,w,X,!1,Y,Z,!1,I,e,aa,J,ca,da,K,ea],exports:{nop:function(){},access:g,frame:p,accParent:O,accTop:q,isolate:P,flashVersion:L,hidden:ga,hasHidden:B,isIE:y,ieVersion:ha,addEvent:x,isMac:Q,isApple:z,isIPad:C,isIPhone:D,isIOS:m,isIOSF:n,isGoogle:E,isAndroid:F,isTouch:R,isChrome:G,chromeVersion:M,isFirefox:H,isOpera:S,isOperaWebkit:l,isSafari:r,isIEMobile:b,isSafari5OrLess:T,screenX:U,outerWidth:V,mozInnerScreenX:W,
msZF:w,ieDomEvents:X,reqAni:N,isRad:!1,isIOSWebView:Y,intersectionAPI:Z,hasSrcDoc:!1,isIOSOrAndroid:I,hasFocus:e,IEVisibility:aa,isWisp:J,wisp:ba,RAFVisibility:ca,asyncFrame:ja,isAsyncFrame:da,mraid:ka,isMraid:K,hasBeacon:ea,frame:p,accParent:O,accTop:q,isolate:P,hasHidden:B,isIE:y,addEvent:x,isMac:Q,isApple:z,isIPad:C,isIPhone:D,isIOS:m,isIOSF:n,isGoogle:E,isAndroid:F,isTouch:R,isChrome:G,isFirefox:H,isOpera:S,isOperaWebkit:l,isSafari:r,isIEMobile:b,isSafari5OrLess:T,screenX:U,outerWidth:V,mozInnerScreenX:W,
msZF:w,ieDomEvents:X,isRad:!1,isIOSWebView:Y,intersectionAPI:Z,hasSrcDoc:!1,isIOSOrAndroid:I,hasFocus:e,IEVisibility:aa,isWisp:J,RAFVisibility:ca,isAsyncFrame:da,isMraid:K,hasBeacon:ea}}}var L={$hash:function(){if(!t){for(var f=N(),v=f.result,f=f.exports,h=[],c=0,a=v.length,e=0,a=a+(6-a%6)%6;c<a;c++)e=e<<1|!!v[c],5==c%6&&(h.push("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789.-".charAt(e)),e=0);for(c in f)L[c]=f[c];t=h.join("")}return t}},t;try{if(!Function("return ("+M+")(1)===1")())throw"Incorrect eval result";
}catch(f){fa.log("toString",f)}return L});
a(e,[c,b],function(n,d){var g=n.window,q=g.document,x=g.setTimeout;d.$hash();return function(a){var c,b,f,l,h,k,y=new Date;b=a.type;var r=a.placeId,z=/\.js(\?|$)/i,A=/\.swf(\?|$)/i,m=d.isIE,t=d.flashVersion,p=m&&10>d.ieVersion,m=!m&&21>t;c="standard"==a.type&&"flash"==a.subtype;var B=d.isSafari&&6.1<=d.safariVersion&&c,C=a.fVer||a.ADFVer||a.version,D=a.ADFPoliteSrc,u=a.sources||a.videoSources,v=["src","ADFFlash","ADFInitFlash","bsrc","ADFBuckup"];b=4==a.behavior?"Slider":b.charAt(0).toUpperCase()+
b.slice(1);c=["AdConstructor","types/"+b];if("Standard"==b){for(b=0;b<v.length;b++)(f=a[v[b]])&&(f.match(A)?l=f:f.match(z)?h=f:k=f);k&&p&&(h=0);k&&p&&(u=0);if(C>t||(k||h)&&(m||B))l=0;l?c.push("contents/FlashTag"):h?c.push("contents/HTML"):u&&c.push("contents/VideoTag");(!l&&!h&&k||D)&&c.push("contents/ImageTag")}n.require(c,function w(b,c){var e,d=b.cbuild;e="function"!==typeof c&&c;r?(e=q.getElementById(r)||e)?(a.placement=e.nextSibling||e.previousSibling,e&&e.parentNode.removeChild(e),d(a)):1E4>
new Date-y?x(function(){p&&(g.inDapMgrIf||g.inDapIF||g.inFIF)?w(b,q.body.firstChild):w(b)},0):n.rethrow("Failed to find placement","noplacement"):d(a)})}});
a(N,[c,h],function(f,g){function e(a){return h(a).random()}function h(a){var e={random:k,int32:function(){var b,a,e=[0,2567483615];if(624<=c)for(a=c=0;624>a;a++)b=d[a]&2147483648|d[(a+1)%624]&2147483647,d[a]=d[(a+397)%624]^b>>>1^e[b&1];b=d[c++];b^=b>>>11;b^=b<<7&2636928640;b^=b<<15&4022730752;return(b^b>>>18)>>>0}},d=[],c;a||(a=Math.round(1E5*((new Date).getTime()+Math.random())));d[0]=a>>>0;for(c=1;a=c-1,624>c;c++)a=d[a]^d[a]>>>30,d[c]=(1812433253*((a&4294901760)>>>16)<<16)+1812433253*
(a&65535)+c,d[c]>>>=0;return e}function k(){return Math.floor(this.int32()/65535)}g.random=f.deprecate(e,"Adform.random is deprecated. Use h/random instead.");return e});
a(L,[c,h],function(e,a){function l(a,c){var f=c?9==c.nodeType?c:c.document:m;0<=a.indexOf('"')&&e.log("xss_detected",a);f.write('<script type="text/javascript" src="'+a+'">\x3c/script>')}function n(e){for(var c=a._prepareBannerDataCB,f={},d="ADFVideoCDN ADFDomainCDN ADFDomain VideoCDN ADFVideoCDNList ADFcmpgnID ADFmembID ADFtagID ADFafbanID ADFBanVer ADFBanVerBak ADFbanID ADFbanPlacID ADFUnloadID ADFClientSiteId ADFGeoData ADFGroupId ADFTemplateVersion ADFTemplateId ADF_ClickEvent".split(" "),
g=d.length-1;0<=g;g--)d[g]in h&&(f[d[g]]=h[d[g]]);var k=a.RMBData={clicktags:""};a._prepareBannerDataCB=function(){for(var b=d.length-1;0<=b;b--)d[b]in f&&(h[d[b]]=f[d[b]]);a.prepareBannerData(e);for(b in k)a.RMBData[b]="clicktags"!=b?k[b]:a.RMBData[b]+k[b];c&&c()};c||l(a.scriptBase+"bootstrap/Adform.BannerData.js?v="+a.cache)}var h=e.window,m=h.document;a.host&&(ADFDynamicDomain=a.host+"/banners/");a.shost&&(ADFTemplateDomain=a.shost+"/banners/");a.ENV={akamaiHost:("https:"==m.location.protocol?
"https://":"http://")+"adformvod-vh.akamaihd.net/i/Banners"};a.Log=a.Log||{sendMessage:e.log};a.loadResource=a.loadResource||l;a.prepareBannerData=a.prepareBannerData||n;return{loadResource:a.loadResource,prepareBannerData:a.prepareBannerData}});
a(M,function(){function f(a){a=a||"";var b=a.split(";oobclicktrack=");b.shift();b.length&&(this.tracks=b);a=a.split("?");this._base=a.shift();this._parts=a.join("?").split(";");this.append=[]}function g(a,b,c){var d=a.length;b+="=";var e,f=b.length;for(c||(b=b.toLowerCase());d--&&(e=a[d].slice(0,f),c||(e=e.toLowerCase()),e!==b););return d}var h=Object.prototype.hasOwnProperty,e=f.prototype;e.copy=function(){var a,b=new f;for(a in this)h.call(this,a)&&(b[a]=this[a]&&this[a].slice?this[a].slice(0):
this[a]);return b};e.get=function(a,b){var c=this._parts,d=g(c,a,b);if(~d)return c[d].slice(a.length+1)};e.set=function(a,b,c){var d=this._parts;c=g(d,a,c);0>c?d.push(a+"="+b):d[c]=d[c].slice(0,a.length+1)+b;return this};e.unset=function(a,b){var c=this._parts,d=g(c,a,b);~d&&c.splice(d,1);return this};e.toString=function(){return this._base+"?"+this._parts.join(";")+this.append.join("")};return f});
a(O,[c,b,L],function(n,c,k){var f=n.window,a=f.document,p=k.loadResource,q=c.isIE&&10>c.ieVersion;return function(c,g){function k(b){b||n.log("dv_not_blocked",g.BN,1)}function r(b){var d=a.createElement("div");d.innerHTML=b;return d.firstChild}function t(b){var d=a.createElement("script");d.src=b;return d}function l(b,a){b.appendChild(a)}var h=a.body,e="_adform_dv_"+ +new Date+"_"+(Math.random()+"").slice(2),m='<script type="text/adtag"><script>'+e+"();</scr+ipt>\x3c/script>";
q&&(m+='<script type="text/passback"><script>'+e+'("P");</scr+ipt>\x3c/script>');f.replaceDocumentWrite&&a.writeln===a.write&&h?(l(h,r(m)),l(h,t(c)),l(h,r("<script>\x3c/script>"))):(a.write(m),p(c),q||a.write("<script>"+e+'("F");\x3c/script>'));f[e]=function(a){f[e]=k;a&&g.set("bsdata",g.BSDATA);p(g.toString())}}});
a(P,[c,b],function(k,l){function b(a,c){for(var d=[],e,f,b,g=0;g<a.length;g++)if(e=a[g])for(var h=0;h<c.length;h++)f=c[h],((b=e[f])||0==b)&&d.push(b);return d}return function(){if(l.accTop){var a=k.window.top,c=a.document,d=c.documentElement,e=c.body,c=b([a,d,e],["pageYOffset","scrollTop"])[0],f=Math.max.apply(null,b([d,e],["scrollHeight","offsetHeight","clientHeight"])),a=b([a,d,e],["innerHeight","clientHeight"])[0];return f==a&&0==c?1:0}}});
a(G,[c,b,h,e,N,L,M,O,P],function(x,y,f,Y,E,e,Z,N,aa){function v(){var a,b;if(r)return r;this.banners={};this.compoundBanners={};try{h.body||h.write("<html><body></body></html>")}catch(d){}a=m.browserLanguage||m.language||0;b=this.getWin();this.settings=[escape(m.systemLanguage||a),escape(a),n?n.width+"X"+n.height:0,y.flashVersion,50*Math.round(b.w/50),50*Math.round(b.h/50),n?n.colorDepth:0,8,3,7,this.hasIframeSanbox()].join("|")}
function O(a){function b(b){z(["3rdparty/vendor/Adform"],function(c){c(a,b)})}var d=a.placeId="+ADFP"+a.adfxid,c=a.innerTagId,f=["types/ThirdParty"],z=x.require;h.write('<i id="'+d+'" style="display:none"></i>');c&&(_adform.push([c+".on.setup",b]),f.push("3rdparty/vendor/Adform"));z(f,function(b){b(a)})}function P(a){var b,d,c=a||f.BannerList&&f.BannerList.shift()||f.RMBData,e={expanding:1,singleExpanding:1,floating:1,tearback:1,interstitial:1};c&&(a=c.type,b=c.behavior,d=c.adfxid||c.ADFid,c._beforeScript=
f._beforeScript,f._beforeScript=!1,{standard:1,expanding:1,singleExpanding:1}[a]&&![0,0,0,1,1][b]&&(c.placeId="+ADFP"+d,b=r.banners[d],h.write('<div id="'+c.placeId+'"'+(b.singleTag?"":' style="width:'+b.width+"px;height:"+b.height+'px;"')+'></div><i style="display:none"></i>')),Y(c),f.ADF_STUB&&e[a]&&x.log("RM_STUB",a,1))}function B(a,b,d){var c=(d=d||h).createElement("div");c.innerHTML='<iframe src="'+a+'" allowtransparency="true" webkitallowfullscreen mozallowfullscreen allowfullscreen marginwidth="0" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no" style="'+
b+'"></iframe>';d.body.appendChild(c.removeChild(c.firstChild))}function Q(a){var b,d,c,e=/\/adfscript/,z=f.ADFIframe&&{src:g.location.href.replace(/cpjs=2/,"cpjs=0")};if(!z)for(b=h.getElementsByTagName("script"),d=b.length;d--&&!z;)(c=b[d]).src&&c.src.match(e)&&-1<c.src.indexOf(a)&&(z=c);return z||{}}function ba(a){var b,d;d=y.asyncFrame;var c=a;if("undefined"!=typeof a.URL){try{b=g.top.location.href.split("#")[0]}catch(f){b=d||g,b=(d=(d=b.location.ancestorOrigins)&&d[d.length-1])||b.document.referrer}b=
b?C(b):a.CREFURL;c=new Z(a.URL);c.append.push("&CREFURL="+b);c.CREFURL=b;c.STUBFILE=a.STUBFILE;c.BSURL=a.BSURL;c.BSDATA=a.BSDATA;c.BN=a.BN;c.ROTSEQ=a.ROTSEQ}return c}function F(a,b){try{if(a){(b=b||[]).push(a);for(var d=0;d<a.frames.length;d++)F(a.frames[d],b);return b}}catch(c){}}function R(a){return E(a+this.id)}function S(a){try{return a.Adform&&a.Adform.ADFUtilInstance}catch(b){}}function ca(){var a=v().banners,b,d,c=[],f=!1,e;for(e in a)T.call(a,e)&&(d=a[e],b||(b=d.cookieID),c.push([d.bn,d.cookieID,
d._host]),a[e].cookieID!=b&&(f=!0));if(f){for(a=0;a<c.length;a++)c[a]=c[a].join("_");x.log("cookies",c.join("|"),1)}}function G(){return(new Date).getTime()}function U(a){try{return da(a)}catch(b){return a}}var r,l,H,I,A,J,K,g=x.window,h=g.document,m=g.navigator,n=g.screen,V=g.setTimeout,ea=g.clearTimeout,L=g.Image,T=Object.prototype.hasOwnProperty,D=e.loadResource,C=g.encodeURIComponent,da=g.decodeURIComponent,W=f.cache,M=[];e=v.prototype;var X={webkitVisibilityState:"webkitvisibilitychange",mozVisibilityState:"mozvisibilitychange",
msVisibilityState:"msvisibilitychange",visibilityState:"visibilitychange"};_adform=g._adform||[];if(f.ADFBannerUtils)return f.ADFBannerUtils;for(A in X)A in h&&(H=A,I=X[A]);e.getCompoundBannerInfo=function(a){return this.compoundBanners["c"+a]||null};e.createBanner=function(a){function b(a){var b=a.url;"stubFileExists"in q||(a.helper&&V(function(){x.log("StubFileError","Cref: "+u+" > Adfserve: "+t+" > bn: "+w)},100),(q.stubFileExists=a.exists)?(b=U(b),B(f.scriptBase+"iframe/recache.html?bv="+W,"position:absolute;width:10px;height:10px;left:-9999px;top:-9999px"),
B(b+"#"+W+"#"+Q(w).src,"position:absolute;top:0;left:0;width:100%;height:100%",y.asyncFrame)):((d=f.RMB)&&(d=d.AdConstructor)&&(d=d.cbuild)||(f.RMB=f.RMB||{},f.RMB.AdConstructor={build:P},f.thirdPartyCB=O),r?N(r,k):D(t)))}var d,c,e,g,t,p=this,l=p.getTagID(),q=p.addNewBanner(l,"undefined"==typeof f.ADFIframe?0:1),k=q.params=ba(a,p);g=k.get("compoundSeqNo");var w=k.BN;a=p.getCompoundBannerInfo(w);var m=p.getPropByBn("smid",w),v=k.ROTSEQ,u=k.CREFURL,n=k.STUBFILE,r=k.BSURL,A;k.tracks&&(q.OOBClickTracks=
k.tracks);k.get("singleTag")&&(q.singleTag=!0,g=g||1,k.set("compoundSeqNo",g));q.compoundSeqNo=g;"prerender"==h[H]&&(k.set("hid",2),q.prerender=!0,h.addEventListener(I,function(){"prerender"!=h[H]&&q.prerender&&(h.removeEventListener(I,arguments.callee,!1),p.registerImpression(q))},!1));g&&(g=p.getRotSeed(),c=g.gen(w),g.compound[w]?e=g.compound[w]:v&&(g.compound[w]=v));k.set("js",1);k.set("adfxid",l);k.set(Math.floor(11E3*Math.random())+";set",p.settings+"|"+aa());c&&k.set("rotseed",c);e&&k.set("rotseq",
C(e));a&&k.set("rotseqno",a.replace("r",""));m&&k.set("smid",m);f.CDNHost&&k.set("cdnhost",C(f.CDNHost));k.set("fd",y.accTop?""===h.title?"2|2":"0|2":"0|0");t=k.toString();u&&n&&!f.ADF_STUB&&(u=U(u).replace(/(:\/\/[^\/]+).*/,"$1"),A=n.HOST?u.split("/")[2]===n.HOST&&p.needStubFile(u):p.needStubFile(u));A?(f.stubFile=b,c=f.shost+"/adfstub/?url="+C(u+n.PATH),D(c),D(f.scriptBase+"extra/StubHelper.js?bv="+f.cache)):(f.ADF_STUB&&x.log("adfstub",u,1),(d=f.RMB)&&(d=d.AdConstructor)&&(d=d.cbuild)||(f.RMB=
f.RMB||{},f.RMB.AdConstructor={build:P},f.thirdPartyCB=O),r?N(r,k):D(t));return q};e.addNewBanner=function(a,b){return this.banners[a]={id:a,type:b,adfserveLoadTime:G()}};e.copyBanner=function(a,b){var d,c=this.banners[a];if(c=c&&c.params||null){c=c.copy();for(d in b)T.call(b,d)&&c.set(d,b[d]);c=this.createBanner(c)}return c};e.wipeOutBanner=function(a){var b=this.banners[a];b&&(l&&(l.id=E(),l.compound&&delete l.compound[b.bn]),delete this.compoundBanners["c"+b.bn],delete this.banners[a])};e.addBannerAttribute=
function(a,b,d){(a=this.banners[a])&&(a[b]=d)};e.getTagID=function(){var a=this.getRotSeed();a.xId||(a.xId=0);return++a.xId+"x"};e.getRotSeed=function(){var a,b,d,c,e;if(!l&&!J){J=!0;try{for(a=F(g.top),b=0,d=a.length;b<d;b++)if(c=a[b],c!=g&&(e=S(c))&&e.getRotSeed){l=e.getRotSeed();break}}catch(f){}l?l.gen=R:l={compound:{},id:E(),gen:R}}J=!1;return l};e.getFlashVersion=x.deprecate(function(){return y.flashVersion},"Utils_getFlash");e.getWin=function(){var a=h.documentElement,b=h.body;return{w:g.innerWidth||
a&&a.clientWidth||b&&b.clientWidth,h:g.innerHeight||a&&a.clientHeight||b&&b.clientHeight}};e.getSettings=function(){return this.settings};e.firePixel=function(a){("undefined"==typeof L?h.createElement("img"):new L).src=a};e.fireTargAdPixel=function(a){var b=this.TargAd||{};b[a]||((this.TargAd=b)[a]=!0,a=a.replace("{gmtr}",Math.floor(9999999999*Math.random())).replace("{gmttzd}",(new Date).getTimezoneOffset()),this.firePixel(a))};e.registerImpression=function(a){var b,d;a&&a.prerender&&(b=a.params.copy(),
b.set("hid",1),a.rotseqno&&b.set("rotseqno",a.rotseqno),d=h.createElement("script"),d.src=b.toString(),d.type="text/javascript",h.body.appendChild(d),delete a.prerender)};e.addCompoundBannerInfo=function(a,b){this.compoundBanners["c"+a]="r"+b};e.setBannerRegisteredStatus=function(a){var b,d,c=this.banners[a];if(c){var e=G(),g=e-c.adfserveLoadTime,t=parseInt(c.serverTime,10),h=f.ADFEventsInstance;c._host=f.host;c.adfserveLoadTime=g;t&&(t+=Math.round(.5*g),c.serverTime=t,c.timeDiff=t-e);c.registered=
1;this.sendLoadMetrics(a);if(c.singleTag&&1==c.compoundSeqNo)for(b=2,d=c.syncMembersCount;b<=d;b++)this.copyBanner(a,{compoundSeqNo:b,compoundImpr:0});try{for(h&&h.register(c),b=0,d=M.length;b<d;b++)M[b].call(this)}catch(l){}0<parseInt(c.cookieID,10)&&(K&&ea(K),K=V(ca,3E3))}};e.onBannerRegisteredStatus=function(a){M.push(a)};e.hasIframeSanbox=function(){var a=this._sandbox;if("number"!=typeof a){a=1;try{g.top.document.getElementById,a=0}catch(b){}this._sandbox=a}return a};e.getPropByBn=function(a,
b){var d,c,e=this.banners;for(d in e)if(c=e[d],c.bn==b&&a in c)return c[a]};e.now=G;e.needStubFile=function(a){var b=g.$sf,d=g.parent,c=this._stub,e=y.asyncFrame,f=/^https?:/,h=g.location.protocol;if(null==c){c=!(g==d||g.inDapMgrIf||g.inDapIF||g.inFIF||b&&b.ext);!c&&e&&(c=!0,d=e.parent);if(c)try{d.document.getElementById,c=!1}catch(l){}c&&(h=h.match(f)?h:null,y.accParent&&!h&&(h=d.location.protocol,h=h.match(f)?h:null),c=a.split("/")[0]===h);this._stub=c}return c};e.getAdfscript=Q;e.getUnloadId=function(a){try{for(var b,
d,c,e,f=F(g.top),h=f.length;h--;)for(c in b=(d=S(f[h]))&&d.banners,b)if(e=b[c],e.bn==a&&1==e.compoundSeqNo)return e.unloadID}catch(l){}};e.sendLoadMetrics=function(a){a=this.banners[a];var b=g.ADFGeoData,d=(f.shost||"").split("/")[0]+"//"+"s1.adform.net/stoat/619/s1.adform.net/load".replace("/load","")+"/bootstrap.js",c=g.performance,d=(d=c&&c.getEntriesByName&&c.getEntriesByName(d))&&d[0]&&d[0].duration;!a.metricsSent&&"string"==typeof b&&.1>Math.random()&&(b=b.split(";"),3==b.length&&((new L).src=f.host+"/jsmetrics/?adfserve="+a.adfserveLoadTime+
(d?"&asset="+parseInt(d,10):"")+"&sid="+b[2]+"&rid="+b[1]+"&cid="+b[0]));a.metricsSent=!0};e.loadFrame=B;e.loadTrackingIframes=function(a){var b=this.getRotSeed();if(a&&a.length&&!b.framesLoaded)for(b.framesLoaded=!0,b=a.length;b--;)B(a[b],"display:none")};e.ADFCreateObjectCallback=function(a,b){return function(){b.apply(a,arguments)}};e.eventRegister=function(){};e.getPosition=function(a){for(var b={x:0,y:0};a;)b.x+=a.offsetLeft,b.y+=a.offsetTop,a=a.offsetParent;return b};e.getScrollXY=function(){var a=
h.body,b=h.documentElement,d={x:0,y:0};"number"==typeof g.pageYOffset?(d.y=g.pageYOffset,d.x=g.pageXOffset):a&&(a.scrollLeft||a.scrollTop)?(d.y=a.scrollTop,d.x=a.scrollLeft):b&&(b.scrollLeft||b.scrollTop)&&(d.y=b.scrollTop,d.x=b.scrollLeft);return d};e.getBrowser=function(){try{var a=m.userAgent;return~m.appVersion.indexOf("MSIE")&&0>a.indexOf("Opera")?"MSIE":~a.indexOf("Safari")?"Safari":~a.indexOf("Opera")?"Opera":~a.indexOf("Netscape")?~m.product.indexOf("Gecko")&&(~m.vendor.indexOf("Firefox")||
~a.indexOf("Firefox"))?"Firefox":"Netscape":void 0}catch(b){}};f.ADFUtilInstance=r=new v;return f.ADFBannerUtils=v.getInstance=v});
a(I,[c,h,G],function(a,e,c){var l=Object.prototype.hasOwnProperty,m=a.window,n=m.document;a={Initialized:!1,InitTime:(new Date).getTime(),Host:e.host||("https:"==n.location.protocol?"https://":"http://")+"track.adform.net",callbacks:[],sendEvent:function(p,f,a,c,h){var d,g,b,k;g=Math.round(((new Date).getTime()-this.InitTime)/1E3);b=q.banners[p];k=e.adRegister&&e.adRegister[p];try{this.notifyAboutEvent.apply(this,arguments)}catch(l){}if(!b&&k)d=k.sendEvent(f,a,c,h);
else if(b&&b.isEventsEnabled){d=b.bn;!b._imprID&&1<b.compoundSeqNo&&(b._imprID=q.getUnloadId(d)||b.unloadID);g=["bn",d,"event",f,"time",(0>g?0:3600<g?3600:g)+"","banner",b.ban,"innerbanner",b.innerban,"asset",a,"name",c,"imprid",b._imprID||b.unloadID,"icid",b.cookieID,"eData",b.eData,"adxvars",b.adxvars,"rnd",Math.floor(1E9*Math.random())];b=0;for(d=[];b<g.length;b+=2)(k=g[b+1])&&d.push(g[b]+"="+encodeURIComponent(k));d=this.Host+"/Serving/Event/?"+d.join("&")+(h||"");(m.Image?new m.Image(1,1):n.createElement("img")).src=
d}return d},Initialize:a.deprecate(function(){this.Initialized=!0},"initEvents",1),registerCallback:function(a,f){"function"==typeof a&&this.callbacks.push([a,f])},unregisterCallback:function(a){var f=this.callbacks,c=f.length;if("function"==typeof a)for(;c--;)f[c][0]==a&&f.splice(c,1)},notifyAboutEvent:function(){for(var a=this.callbacks.slice(),c=0,e=a.length;c<e;c++)a[c][0].apply(a[c][1]||this,arguments)}};var q=c();if(c=e.Events){for(var h in a)l.call(a,h)&&!l.call(c,h)&&(c[h]=a[h]);c.sendEvent=
a.sendEvent}else c=e.Events=a;e.ADFEvents2||(e.ADFEvents2=c);return a});
a(J,[c,h],function(g,b){function d(c){try{var e=c.URL,d=c.BN,h,a,n,k;c=/\/adfscript/;var l=b.ADFIframe&&{src:r.location.href.replace(/cpjs=2/,"cpjs=0")};if(!l)for(a=m.getElementsByTagName("script"),n=a.length;n--&&!l;)(k=a[n]).src&&k.src.match(c)&&-1<k.src.indexOf(d)&&(l=k);h=l||m.currentScript||{};var f=m.createElement("div");a=h;var p,t,q,u,e=e.split(";");e[0]+=";srctype=6";for(e=e.join(";");a;)p="BODY"==a.nodeName,t="HEAD"==a.nodeName,a=!(p||t)&&a.parentNode;p?(q=h.parentNode,u=
h):q=m.body;f.innerHTML='<a href="'+b.host+"/C/?bn="+d+';C=0"><img src="'+e+'"></a>';q.insertBefore(f.firstChild,u||null);g.log("fallback",d)}catch(v){g.rethrow(v,"fallback_error")}}var f,r=g.window,m=r.document;g.require(["$ignore"],function(){var c=b.ADFBannerParams;f||(b.ADFUtilInstance||(b.ADFUtilInstance={}),b.ADFBanner||(b.ADFBanner=d),d(c&&c.length?c.shift():b.ADFBannerData))});return{cancel:function(){f=!0},write:d}});
a(w,[h],function(l){function g(){}function h(b){b?this._events&&this._events[b]&&delete this._events[b]:delete this._events;return this}function k(b){var a=this._events;a||(this._events=a={});return a[b]||(a[b]=[])}var m=Array.prototype.slice,f=g.prototype;l.RMB.EventEmitter=g;f.emit=function(b){var a,c,d,e=this._events;if(e&&(e=e[b])&&(c=e.length))for(d=m.call(arguments,1),e=e.slice(),a=0;a<c;a++)e[a].apply(this,d);return this};f.on=function(b,a){this.emit("newListener",b,a);k.call(this,
b).push(a);return this};f.once=function(b,a){var c=function(){return a.apply(this.off(b,c),arguments)};c._oncep=a;return this.on(b,c)};f.off=function(b,a){var c,d=(c=this._events)&&c[b];if(d){for(c=d.length;c--;)d[c]!=a&&d[c]._oncep!=a||d.splice(c,1);d.length||h.call(this,b);this.emit("removeListener",b,a)}return this};f.clear=h;f.list=k;return g});
a(y,[c,G],function(t,x){function m(g,l){for(var a in l)l.hasOwnProperty(a)&&("object"==typeof l[a]?("object"!=typeof g[a]&&(g[a]={}),m(g[a],l[a])):g[a]=l[a])}var q=t.window,y=q.parent,r={useClose:"expImage.useClose",overlay:"overlay",wallpaper:"options.wallpaper",x:"options.x",y:"options.y",hidden:"options.hidden",position:"options.position",adNotice:"options._adNotice",fixedBounding:"options.fixedBounding",resizeInFIF:"options.iabResize",panel:"panel",responsive:"options.responsive",
testPlace:"options.testPlace"};return function(g,l){var a,u,h,f,n,c,d,b,v,k;d=g.options;b=d.bn;c=x();var e;try{e=((d.iab?y:q)._adform||[]).slice(0)}catch(w){e=[]}var z=/(?:(\d+x|\d+#\d+|#[-_0-9a-z]+|\d+))?\.?(.*)/i,p={};d.iab&&e.push.apply(e,q._adform||[]);c&&c.getPropByBn&&(c=c.getPropByBn("multiPanel",b))&&e.push.apply(e,c);if(c=(d.userParams||{})._adform)try{if((c=Function("return ("+c+")")())&&"object"==typeof c)(e=e||[]).push([d.xId,c]);else throw Error("_adform from userParams should be an object");
}catch(w){t.rethrow(w,"user_params")}if("[object Array]"==Object.prototype.toString.call(e)&&e.length){d=l||["",b,"#"+d.seqNo,b+"#"+d.seqNo,d.xId];b=0;c=d.length;for(v=e.length;b<c;b++)p[d[b]]={};for(b=0;b<v;b++)if(a=e[b][0].match(z),u=p[a[1]||""]){h=e[b][1];if(a[2]){a=a[2].split(".");for(n=f={};1<a.length;)f=f[a.shift()]={};f[a[0]]=h;h=n}if(a=h.on)for(k in a){if("function"==typeof a[k])g.events.on(k,a[k])}else if(h.init)g.events.on("init",h.init);a={};for(f in h)r[f]&&(a[f]=h[f]);m(u,a)}k=p[d[0]];
for(b=1;b<c;b++)m(k,p[d[b]]);for(b in r)if(b in k){a=r[b].split(".");for(n=f={};1<a.length;)f=f[a.shift()]={};f[a[0]]=k[b];m(g,n)}}}});
a(u,[c,b],function(d,f){return function(a,b){var c=d.window,g=c.navigator,e=c.Image;try{f.hasBeacon?g.sendBeacon(a,""):((new e).src=a,b&&c!=b&&((new b.Image).src=a))}catch(h){(new e).src=a,d.log("beacon",h+"_"+a,.1)}}});
a(K,[c,h,G,w,y,u],function(v,q,z,I,J,K){function t(c){for(var d=0,k=c.length;d<k;d++){var a=c[d],l=void 0,p=void 0,e,h,f,t=q.scriptBase,u=q.cache,b,g,r;f=void 0;h=a.xId;var A=a.externalScripts,B=a.trackingPixelUrls;b=a.banner;var w=b.backup,m=b.type,H=b.innerTagId;g=b.clickUrls;var z=a.visibility.testMode,G=a.trackingIframeUrls;r=a.geoLocation;var n={};e=a.csImpressionUrl;var C=x.banners[h];A&&(l=A.before,p=A.after);l&&(D(l),q._beforeScript=
!0);x.loadTrackingIframes(G);C&&(E(L,a,C),C.isDSPTag="dsp"===a.impressionType,x.setBannerRegisteredStatus(h));if("thirdparty"===m.type){b={bn:b.tagId,xId:h,bannerId:b.id};g={adfxid:h,options:b};H&&(g.innerTagId=H);r=g.events=new I;a=a.banner.script;J(g,[b.bn]);q.thirdPartyCB&&q.thirdPartyCB(g);try{r.emit("setup",g)}catch(F){v.rethrow(F,"setup")}try{(f=b.wrapper)?y.write(M(f,a)):y.write(a)}catch(F){v.rethrow(F,"thirdPartyWrite")}e&&K(e)}else if("standard"!=m.type||"image"!=m.subType&&"flash"!=m.subType&&
"html"!=m.subType)v.log("rollback",b.tagId+" banner not rendered",1);else{f=b.properties;f={type:m.type,subtype:m.subType,landingPageTarget:f.landingTarget,ADFFlash:b.asset&&b.asset.url||b.url,ADFBuckupClickURL:w&&w.clickUrl||a.clickUrl,width:b.size.width,height:b.size.height,ADFid:h,ADFban:b.tagId,bannerAlign:f.align,clicktags:n,flashvars:n,defaultClickTAG:g[0]&&g[0].name,css:t+"assets/css/Adform.RMB.css?bv="+u,quality:f.quality,wmode:f.wMode,fVer:f.flashVersion};w&&(f.ADFBuckup=w.url);e=0;for(h=
g.length;e<h;e++)n[g[e].name]=encodeURIComponent(g[e].url);E(N,a,n);n.domain=encodeURIComponent(a.staticContentUrl);n.bn=b.tagId;n.geo=[r.city.id,r.region.id,r.country.id].join(";");q.RMB.AdConstructor.build(f)}if(B)for(e=0,h=B.length;e<h;e++)x.fireTargAdPixel(B[e]);p&&D(p);z&&D([t+"unload/Adform.Inscreen.js?"+u])}}function u(){G.apply(this,arguments);t(arguments)}function D(c){for(var d=0;d<c.length;d++)y.write('<script src="'+c[d]+'">\x3c/script>')}function E(c,d,k){var a,l;for(a in c)l=c[a],"string"===
typeof l?null!=d[a]&&(k[l]=d[a]):d[a]&&E(l,d[a],k)}function M(c,d){var k=y.createElement("div");k.innerHTML=c;var a=k.firstChild;a.innerHTML=d;return a.firstChild&&1==a.firstChild.nodeType?k.innerHTML:d}var p=v.window,y=p.document,G=Array.prototype.push,x=z(),L={visitor:{cookieId:"cookieID",isMobile:"isMobile"},csImpressionUrl:"csImpressionUrl",eData:"eData",uData:"uData",interactionId:"unloadID",visibility:{sendUnload:"sendUnloadData",area:"visibilityArea",time:"visibilityTime"},serverTime:"serverTime",
banner:{id:"ban",version:"bannerVersion",template:{dcoEngineId:"dcoEngineId"},size:{width:"width",height:"height"},rotationSeqenceNumber:"rotseqno",smId:"smid",tagId:"bn",campaignId:"pm",membershipId:"ms",bannerPlacementId:"bnpl",isEventEnabled:"isEventsEnabled"},isAdNoticeEnabled:"adNotice",publisher:{adxvars:"adxvars",publisherUnloadData:"publisherUnloadData",visibility:{area:"publisherVisibilityArea",time:"publisherVisibilityTime"}},dsp:{inventorySourceId:"rtbInventorySourceId",requestId:"rtbReqId",
rtbdata:"rtbdata",rtbwp:"rtbwp"},disableFlash:"disableFlash"},N={banner:{clientSiteId:"cid",template:{groupId:"gid",version:"tv",id:"tid"},version:"bv",campaignId:"ADFcmpgnID",membershipId:"ADFmembID",id:"ADFbanID",bannerPlacementId:"ADFbanPlacID",properties:{wMode:"wmode"},dynamicAdContent:"dynamicAdContent"},xId:"ADFid",interactionId:"unloadID",trackingSetupId:"trackingSetupId"};return function(){var c=p.adfjsonbanners;c?(c.push=u,t(c)):(c=[],c.push=u,p.adfjsonbanners=c)}});
a(H,[c,h,I,J,G,K],function(g,a,c,f,h,k){function d(){var b=a.ADFBannerParams,e=b&&b.length?b.shift():a.ADFBannerData;if(e)try{h().createBanner(e)}catch(c){g.rethrow(c,"create_banner"),f.write(e)}b&&b.length&&d()}a.ADFBanner||(a.ADFBanner=d,a.ADFBanner());k();c.IE=9;f.cancel();return d});
a(d,function(){return"8IC-4gAAAAUAA"});
})(_adfq.define,"Adform","$boot","$env","$main","h/random","bootstrap/Global","bootstrap/URL","bootstrap/dv","bootstrap/isAppView","bootstrap/Utils","bootstrap/Events","bootstrap/Fallback","common/EventEmitter","api/ARMA","h/beacon","bootstrap/adfjsonbanners","bootstrap/Banner","$ignore");