;(function(){var dfltPluginCfg={"sourceFile":"upload","info":true};var dfltGlobalCfg={"site":582425,"log":"logc408","logSSL":"logs1408","domain":"xiti.com","secure":false,"pixelPath":"/hit.xiti","disableCookie":false,"cookieSecure":false,"cookieDomain":"","preview":false,"plgs":["Campaigns","Clicks","ClientSideUserId","ContextVariables","IdentifiedVisitor","InternalSearch","OnSiteAds","Page","RichMedia","SalesTracker"],"lazyLoadingPath":"","documentLevel":"document","redirect":false,"activateCallbacks":true,"medium":"","ignoreEmptyChapterValue":false,"base64Storage":false};(function(a,b){a.ATInternet=a.ATInternet||{};a.ATInternet.Tracker=a.ATInternet.Tracker||{};a.ATInternet.Tracker.Plugins=a.ATInternet.Tracker.Plugins||{}})(window);
var Utils=function(){function a(g){var b=typeof g;if("object"!==b||null===g)return"string"===b&&(g='"'+g+'"'),String(g);var k,c,m=[],e=g&&g.constructor===Array;for(k in g)g.hasOwnProperty(k)&&(c=g[k],b=typeof c,"function"!==b&&"undefined"!==b&&("string"===b?c='"'+c.replace(/[^\\]"/g,'\\"')+'"':"object"===b&&null!==c&&(c=a(c)),m.push((e?"":'"'+k+'":')+String(c))));return(e?"[":"{")+String(m)+(e?"]":"}")}var b=this;b.cloneSimpleObject=function n(a,c){if("object"!==typeof a||null===a||a instanceof Date)return a;
var m=new a.constructor||a.constructor(),e;for(e in a)a.hasOwnProperty(e)&&(void 0===e||c&&void 0===a[e]||(m[e]=n(a[e])));return m};b.jsonSerialize=function(b){return"undefined"!==typeof JSON&&JSON.stringify?JSON.stringify(b):a(b)};b.jsonParse=function(a){try{if("undefined"!==typeof JSON&&JSON.parse)return JSON.parse(a);var b;b=null===a?a:"string"===typeof a?(new Function("return "+a))():!1;return b}catch(c){return null}};b.arrayIndexOf=function(a,b){return Array.indexOf?a.indexOf(b):function(a){if(null==
this)throw new TypeError;var b=Object(this),e=b.length>>>0;if(0===e)return-1;var f=0;1<arguments.length&&(f=Number(arguments[1]),f!=f?f=0:0!=f&&Infinity!=f&&-Infinity!=f&&(f=(0<f||-1)*Math.floor(Math.abs(f))));if(f>=e)return-1;for(f=0<=f?f:Math.max(e-Math.abs(f),0);f<e;f++)if(f in b&&b[f]===a)return f;return-1}.apply(a,[b])};b.uuid=function(){return{v4:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;return("x"===a?b:b&3|8).toString(16)})},
num:function(a){var b=new Date,c=function(a){a-=100*Math.floor(a/100);return 10>a?"0"+a:a};return c(b.getHours())+""+c(b.getMinutes())+""+c(b.getSeconds())+""+function(a){return Math.floor((9*Math.random()+1)*Math.pow(10,a-1))}(a-6)}}};b.getObjectKeys=function(a){var b=[],c;for(c in a)a.hasOwnProperty(c)&&b.push(c);return b};b.completeFstLevelObj=function(a,b,c){if(a){if(b)for(var m in b)!b.hasOwnProperty(m)||a[m]&&!c||(a[m]=b[m])}else a=b;return a};b.isPreview=function(){return window.navigator&&
"preview"===window.navigator.loadPurpose};b.isPrerender=function(a){var d,c=!1,m=["webkit","ms"];if("prerender"===document.visibilityState)d="visibilitychange";else for(var e=0;e<m.length;e++)"prerender"===document[m[e]+"VisibilityState"]&&(d=m[e]+"visibilitychange");if("undefined"!==typeof d){var f=function(c){a(c);b.removeEvtListener(document,d,f)};b.addEvtListener(document,d,f);c=!0}return c};var h=b.addEvtListener=function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+
b,c)},d=b.removeEvtListener=function(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c)};b.loadScript=function(a,b){var c;b=b||function(){};c=document.createElement("script");c.type="text/javascript";c.src=a.url;c.async=!1;c.defer=!1;c.onload=c.onreadystatechange=function(a){a=a||window.event;if("load"===a.type||/loaded|complete/.test(c.readyState)&&(!document.documentMode||9>document.documentMode))c.onload=c.onreadystatechange=c.onerror=null,b(null,
a)};c.onerror=function(a,f,m){c.onload=c.onreadystatechange=c.onerror=null;b({msg:"script not loaded",event:a})};var m=document.head||document.getElementsByTagName("head")[0];m.insertBefore(c,m.lastChild)};b.hashcode=function(a){var b=0;if(0===a.length)return b;for(var c=0;c<a.length;c++)var m=a.charCodeAt(c),b=(b<<5)-b+m,b=b&b;return b};b.setLocation=function(a){var b=a.location;a=window[a.target]||window;b&&(a.location.href=b)};b.dispatchCallbackEvent=function(a){var b;"function"===typeof window.Event?
b=new Event("ATCallbackEvent"):(b=document.createEvent("Event"),b.initEvent&&b.initEvent("ATCallbackEvent",!0,!0));b&&(b.name=a,document.dispatchEvent(b))};b.addCallbackEvent=function(a){h(document,"ATCallbackEvent",a)};(function(){function a(b,c){c=c||{bubbles:!1,cancelable:!1,detail:void 0};var m=document.createEvent("CustomEvent");m.initCustomEvent(b,c.bubbles,c.cancelable,c.detail);return m}if("function"===typeof window.CustomEvent)return!1;a.prototype=window.Event.prototype;window.CustomEvent=
a})();b.addOptOutEvent=function(a,d){b.ATOptOutEvent=new CustomEvent("ATOptOutEvent",{detail:{name:"clientsideuserid",id:d}});h(document,"ATOptOutEvent",a)};b.removeOptOutEvent=function(a){d(document,"ATOptOutEvent",a)};b.dispatchOptOutEvent=function(a){b.optedOut=a;b.ATOptOutEvent=b.ATOptOutEvent||new CustomEvent("ATOptOutEvent",{detail:{name:"clientsideuserid",id:-1}});document.dispatchEvent(b.ATOptOutEvent)};b.userOptedOut=function(){b.dispatchOptOutEvent(!0)};b.userOptedIn=function(){b.dispatchOptOutEvent(!1)};
b.isOptedOut=function(){return!!b.optedOut};b.optedOut=null;b.ATOptOutEvent=null};window.ATInternet.Utils=new Utils;
var BuildManager=function(a){var b=this,h=function(a,c,f){a="&"+a+"=";return{param:a,paramSize:a.length,str:c,strSize:c.length,truncate:f}},d=function(c,b){var f="",g=0,p=!0,l;for(l in c)if(c.hasOwnProperty(l)){var q=c[l];if(q){var p=!1,d=b-g;if(q.strSize+q.paramSize<d)f+=q.param+q.str,g+=q.strSize+q.paramSize,c[l]=void 0,p=!0;else{q.truncate?(f+=q.param+q.str.substr(0,d),c[l].str=q.str.substr(d,q.strSize-1),c[l].strSize=c[l].str.length):q.strSize+q.paramSize>b&&(a.emit("Tracker:Hit:Build:Error",
{lvl:"ERROR",msg:'Too long parameter "'+q.param+'"',details:{value:q.str}}),c[l].str=c[l].str.substr(0,b-q.paramSize-1),c[l].strSize=c[l].str.length);break}}else p=!0}return[f,p?null:c]},g=["ati","atc","pdtl","stc","dz"],n=function(c,b,f){var r=function(a){if(a==={})return"";var l=[],c;c={};var b=0,f=!1,p=void 0,e,m,r;for(r in a)if(a.hasOwnProperty(r)){var k=a[r].value;"function"===typeof k&&(k=k());k=k instanceof Array?k.join(a[r].options.separator||","):"object"===typeof k?window.ATInternet.Utils.jsonSerialize(k):
"undefined"===typeof k?"undefined":k.toString();a[r].options.encode&&(k=encodeURIComponent(k));var n=h(r,k,-1<window.ATInternet.Utils.arrayIndexOf(g,r)),b=b+(n.paramSize+n.strSize);if(a[r].options.last)1490<k.length&&k.substr(0,1490),e=r,m=n;else if(c[r]=n,1500<c[r].paramSize+c[r].strSize&&!c[r].truncate){f=!0;p=r;break}}e&&(c[e]=m);c=[c,b,f,p];a=c[0];if(c[2])c=c[3],a=a[c],a.str=a.str.substr(0,1450),a.strSize=1450,b={},b.mherr=h("mherr","1",!1),b[c]=a,l.push(d(b,1500)[0]);else if(c=d(a,1500),null===
c[1])l=c[0];else for(l.push(c[0]);null!==c[1];)c=d(a,1500),l.push(c[0]);return l},p="";a.buffer.presentInFilters(b,"hitType")||(b=a.buffer.addInFilters(b,"hitType",["page"]));b=a.buffer.addInFilters(b,"hitType",["all"]);var l;if(c){b=a.buffer.addInFilters(b,"permanent",!0);b=a.buffer.get(b,!0);for(l in c)c.hasOwnProperty(l)&&(b[l]={value:c[l],options:{}});p=r(b)}else for(l in b=a.buffer.get(b,!0),p=r(b),b)b.hasOwnProperty(l)&&!b[l].options.permanent&&a.buffer.del(l);f&&f(p)},k=function(c){var b=a.getConfig("secure"),
f="https:"===document.location.protocol,f=b||f?a.getConfig("logSSL"):a.getConfig("log"),g=a.getConfig("baseURL"),p=a.getConfig("domain"),l=a.getConfig("pixelPath"),q=a.getConfig("site");(g||f&&p&&l)&&q?c&&c(null,(g?g:(b?"https://":"//")+f+("."+p)+l)+("?s="+q)):c&&c({message:"Config error"})},c=function(a,c,b){k(function(g,p){g?b&&b(g):n(a,c,function(a){var c=[],g=ATInternet.Utils.uuid().num(13);if(a instanceof Array)if(1===a.length)c.push(p+"&mh=1-2-"+g+a[0]);else for(var e=1;e<=a.length;e++)c.push(p+
"&mh="+e+"-"+a.length+"-"+g+a[e-1]);else c.push(p+a);b&&b(null,c)})})};b.send=function(g,e){c(g,e,function(c,g){if(c)a.emit("Tracker:Hit:Build:Error",{lvl:"ERROR",msg:c.message,details:{hits:g}});else for(var p=0;p<g.length;p++)b.sendUrl(g[p])})};b.sendUrl=function(c){var b=function(c,b){return function(){return function(l){a.emit(c,{lvl:-1===c.indexOf("Error")?"INFO":"ERROR",details:{hit:b,event:l}})}}()},f=new Image;f.onload=b("Tracker:Hit:Sent:Ok",c);f.onerror=b("Tracker:Hit:Sent:Error",c);f.src=
c}},TriggersManager=function(){function a(a,b,d){for(var c=[],m=0;m<a.length;m++)a[m].callback(b,d),a[m].singleUse||c.push(a[m]);return c}function b(a,d,k,c){var m=a.shift();if("*"===m)return d["*"]=d["*"]||[],d["*"].push({callback:k,singleUse:c}),d["*"].length-1;if(0===a.length)return b([m,"*"],d,k,c);d["*"]=d["*"]||[];d[m]=d[m]||{};return b(a,d[m],k,c)}function h(b,d,k,c){var m=d.shift();"*"!==m&&(0===d.length?h(b,[m,"*"],k,c):k[m]&&(k[m]["*"]=a(k[m]["*"],b,c),h(b,d,k[m],c)))}var d={};this.on=function(a,
n,k){k=k||!1;return b(a.split(":"),d,n,k)};this.emit=function(b,n){d["*"]&&(d["*"]=a(d["*"],b,n));h(b,b.split(":"),d,n)}},PluginsManager=function(a){var b={},h={},d=0,g={},n=0,k=this.load=function(l,f){"function"===typeof f?"undefined"===typeof a.getConfig.plgAllowed||0===a.getConfig.plgAllowed.length||-1<a.getConfig.plgAllowed.indexOf(l)?(b[l]=new f(a),h[l]&&b[l]&&(h[l]=!1,d--,b[l+"_ll"]&&c(l+"_ll"),0===d&&a.emit("Tracker:Plugin:Lazyload:File:Complete",{lvl:"INFO",msg:"LazyLoading triggers are finished"})),
a.emit("Tracker:Plugin:Load:"+l+":Ok",{lvl:"INFO"})):a.emit("Tracker:Plugin:Load:"+l+":Error",{lvl:"ERROR",msg:"Plugin not allowed",details:{}}):a.emit("Tracker:Plugin:Load:"+l+":Error",{lvl:"ERROR",msg:"not a function",details:{obj:f}});return a},c=this.unload=function(c){b[c]?(b[c]=void 0,a.emit("Tracker:Plugin:Unload:"+c+":Ok",{lvl:"INFO"})):a.emit("Tracker:Plugin:Unload:"+c+":Error",{lvl:"ERROR",msg:"not a known plugin"});return a},m=this.isLazyloading=function(a){return a?!0===h[a]:0!==d},e=
function(a){return r(a)?(f(a),!0):!1},f=function(c){h[c]=!0;d++;ATInternet.Utils.loadScript({url:a.getConfig("lazyLoadingPath")+c+".js"})},r=function(a){return!b[a]&&!m(a)&&(b[a+"_ll"]?!0:!1)},p=function(a){g[a]?g[a]++:g[a]=1;n++};this.isExecWaitingLazyloading=function(){return 0!==n};a.exec=this.exec=function(c,q,d,e){var k=null,h=function(a,c,f,l){c=c.split(".");b[a]&&b[a][c[0]]&&(k=1<c.length&&b[a][c[0]][c[1]]?b[a][c[0]][c[1]].apply(b[a],f):b[a][c[0]].apply(b[a],f));l&&l(k)},w=function(c,b,f,l){p(c);
a.onTrigger("Tracker:Plugin:Load:"+c+":Ok",function(){h(c,b,f,function(b){g[c]--;n--;0===n&&a.emit("Tracker:Plugin:Lazyload:Exec:Complete",{lvl:"INFO",msg:"All exec waiting for lazyloading are done"});l&&l(b)})},!0)};r(c)?(w(c,q,d,e),f(c)):m(c)?w(c,q,d,e):h(c,q,d,e)};this.waitForDependencies=function(c,f){var d=function(a){for(var c={mcount:0,plugins:{}},f=0;f<a.length;f++)b.hasOwnProperty(a[f])||(c.mcount++,c.plugins[a[f]]=!0);return c}(c);if(0===d.mcount)a.emit("Tracker:Plugin:Dependencies:Loaded",
{lvl:"INFO",details:{dependencies:c}}),f();else for(var p in d.plugins)d.plugins.hasOwnProperty(p)&&(a.emit("Tracker:Plugin:Dependencies:Error",{lvl:"WARNING",msg:"Missing plugin "+p}),a.onTrigger("Tracker:Plugin:Load:"+p,function(a,c){var b=a.split(":"),l=b[3];"Ok"===b[4]&&(d.plugins[l]=!1,d.mcount--,0===d.mcount&&f())},!0),e(p))};this.init=function(){for(var a in ATInternet.Tracker.pluginProtos)ATInternet.Tracker.pluginProtos.hasOwnProperty(a)&&k(a,ATInternet.Tracker.pluginProtos[a])}},CallbacksManager=
function(a){var b={};this.init=function(){if(a.getConfig("activateCallbacks")){var d=a.getConfig("callbacks");(function(){if("undefined"!==typeof d&&d.include instanceof Array)for(var a=0;a<d.include.length;a++)ATInternet.Callbacks&&ATInternet.Callbacks.hasOwnProperty(d.include[a])&&(b[d.include[a]]={"function":ATInternet.Callbacks[d.include[a]]},ATInternet.Tracker.callbackProtos[d.include[a]]||(ATInternet.Tracker.callbackProtos[d.include[a]]=b[d.include[a]]));else for(a in ATInternet.Callbacks)ATInternet.Callbacks.hasOwnProperty(a)&&
(b[a]={"function":ATInternet.Callbacks[a]},ATInternet.Tracker.callbackProtos[a]||(ATInternet.Tracker.callbackProtos[a]=b[a]));if("undefined"!==typeof d&&d.exclude instanceof Array)for(a=0;a<d.exclude.length;a++)b[d.exclude[a]]&&(b[d.exclude[a]]=void 0);for(var n in b)b.hasOwnProperty(n)&&b[n]&&h(n,b[n]["function"])})();ATInternet.Utils.addCallbackEvent(function(a){if(a.name){var b=!0;"undefined"!==typeof d&&(d.include instanceof Array&&-1===ATInternet.Utils.arrayIndexOf(d.include,a.name)&&(b=!1),
d.exclude instanceof Array&&-1!==ATInternet.Utils.arrayIndexOf(d.exclude,a.name)&&(b=!1));if(ATInternet.Callbacks&&ATInternet.Callbacks.hasOwnProperty(a.name)){var k={};k[a.name]={"function":ATInternet.Callbacks[a.name]};b&&h(a.name,k[a.name]["function"]);ATInternet.Tracker.callbackProtos[a.name]||(ATInternet.Tracker.callbackProtos[a.name]=k[a.name])}}})}};var h=this.load=function(b,g){"function"===typeof g?(new g(a),a.emit("Tracker:Callback:Load:"+b+":Ok",{lvl:"INFO",details:{obj:g}})):a.emit("Tracker:Callback:Load:"+
b+":Error",{lvl:"ERROR",msg:"not a function",details:{obj:g}});return a}},BufferManager=function(a){var b={};this.set=function(a,d,k){k=k||{};k.hitType=k.hitType||["page"];b[a]={value:d,options:k}};var h=function(a,b,d){return(a=window.ATInternet.Utils.cloneSimpleObject(a[b]))&&!d?a.value:a},d=function n(a,c){if(!(a&&c instanceof Array&&a instanceof Array))return[];if(0===a.length)return c;var d=a[0],e,f=[],r=window.ATInternet.Utils.cloneSimpleObject(a);r.shift();for(var p=0;p<c.length;p++)if("object"!==
typeof d[1])b[c[p]]&&b[c[p]].options[d[0]]===d[1]&&f.push(c[p]);else{e=d[1].length;for(var l=0;l<e;l++)if(b[c[p]]&&b[c[p]].options[d[0]]instanceof Array&&0<=window.ATInternet.Utils.arrayIndexOf(b[c[p]].options[d[0]],d[1][l])){f.push(c[p]);break}}return n(r,f)};this.get=function(a,k){var c={};if("string"===typeof a)c=h(b,a,k);else for(var m=d(a,window.ATInternet.Utils.getObjectKeys(b)),e=0;e<m.length;e++)c[m[e]]=h(b,m[e],k);return c};this.presentInFilters=function k(a,b){return a&&0!==a.length?a[0][0]===
b?!0:k(a.slice(1),b):!1};this.addInFilters=function c(a,b,f,d){if(!a||0===a.length)return d?[]:[[b,f]];var p=a[0][0],l=a[0][1];p===b&&(l instanceof Array&&!(-1<window.ATInternet.Utils.arrayIndexOf(l,f[0]))&&l.push(f[0]),d=!0);return[[p,l]].concat(c(a.slice(1),b,f,d))};this.del=function(a){b[a]=void 0};this.clear=function(){b={}}},Tag=function(a,b,h){b=b||{};var d=this;d.version="5.11.2";var g=window.ATInternet.Utils.cloneSimpleObject(b);d.triggers=new TriggersManager(d);d.emit=d.triggers.emit;d.onTrigger=
d.triggers.on;var n=window.ATInternet.Utils.cloneSimpleObject(dfltGlobalCfg)||{},k;for(k in a)a.hasOwnProperty(k)&&(n[k]=a[k]);d.getConfig=function(a){return n[a]};d.setConfig=function(a,b,e){void 0!==n[a]&&e||(d.emit("Tracker:Config:Set:"+a,{lvl:"INFO",details:{bef:n[a],aft:b}}),n[a]=b)};d.configPlugin=function(a,b,e){n[a]=n[a]||{};for(var f in b)b.hasOwnProperty(f)&&void 0===n[a][f]&&(n[a][f]=b[f]);e&&(e(n[a]),d.onTrigger("Tracker:Config:Set:"+a,function(a,c){e(c.details.aft)}));return n[a]};d.getContext=
function(a){return g[a]};d.setContext=function(a,b){d.emit("Tracker:Context:Set:"+a,{lvl:"INFO",details:{bef:g[a],aft:b}});g[a]=b};d.delContext=function(a,b){d.emit("Tracker:Context:Deleted:"+a+":"+b,{lvl:"INFO",details:{key1:a,key2:b}});if(a)g.hasOwnProperty(a)&&(b?g[a]&&g[a].hasOwnProperty(b)&&(g[a][b]=void 0):g[a]=void 0);else if(b)for(var e in g)g.hasOwnProperty(e)&&g[e]&&g[e].hasOwnProperty(b)&&(g[e][b]=void 0)};d.plugins=new PluginsManager(d);d.buffer=new BufferManager(d);d.setParam=d.buffer.set;
d.getParams=function(a){return d.buffer.get(a,!1)};d.getParam=d.buffer.get;d.delParam=d.buffer.del;d.builder=new BuildManager(d);d.sendHit=d.builder.send;d.sendUrl=d.builder.sendUrl;d.callbacks=new CallbacksManager(d);d.setParam("ts",function(){return(new Date).getTime()},{permanent:!0,hitType:["all"]});d.getConfig("disableCookie")&&d.setParam("idclient","xxxxxx-NO",{permanent:!0,hitType:["all"]});d.getConfig("medium")&&d.setParam("medium",d.getConfig("medium"),{permanent:!0,hitType:["all"]});d.plugins.init();
d.callbacks.init();ATInternet.Tracker.instances.push(d);d.emit("Tracker:Ready",{lvl:"INFO",msg:"Tracker initialized",details:{tracker:d,args:{config:a,context:b,callback:h}}});h&&h(d)};ATInternet.Tracker.Tag=Tag;ATInternet.Tracker.instances=[];ATInternet.Tracker.pluginProtos={};
ATInternet.Tracker.addPlugin=function(a,b){b=b||ATInternet.Tracker.Plugins[a];if(!ATInternet.Tracker.pluginProtos[a]){ATInternet.Tracker.pluginProtos[a]=b;for(var h=0;h<ATInternet.Tracker.instances.length;h++)ATInternet.Tracker.instances[h].plugins.load(a,b)}};ATInternet.Tracker.delPlugin=function(a){if(ATInternet.Tracker.pluginProtos[a]){ATInternet.Tracker.pluginProtos[a]=void 0;for(var b=0;b<ATInternet.Tracker.instances.length;b++)ATInternet.Tracker.instances[b].plugins.unload(a)}};
ATInternet.Tracker.callbackProtos={};
}).call(window);;(function(){var dfltPluginCfg={"lifetime":30,"lastPersistence":true,"listEventsForExec":[],"domainAttribution":true,"info":true};var dfltGlobalCfg={"visitLifetime":30,"redirectionLifetime":30};window.ATInternet.Tracker.Plugins.Campaigns=function(a){a.setConfig("visitLifetime",dfltGlobalCfg.visitLifetime,!0);a.setConfig("redirectionLifetime",dfltGlobalCfg.redirectionLifetime,!0);var b={},h,d;a.configPlugin("Campaigns",dfltPluginCfg||{},function(a){b=a});var g,n,k,c,m,e,f,r,p,l,q,u,z,y=function(b,c,f){var l=null;a.plugins.exec(b,c,f,function(a){l=a});return l},s=function(a,b){return y("Cookies",a,b)},w=function(a,b){return y("Utils",a,b)},x=function(a,b){var c=s(d,[a]);if(null!==c)return"object"===
typeof c&&!(c instanceof Array);s(h,[a,{},b]);return!0},A=function(b,c){var f=a.getContext("campaigns")||{};f[b]=c;a.setContext("campaigns",f)},v=function(y){h="set"+(b.domainAttribution?"":"Private");d="get"+(b.domainAttribution?"":"Private");g=s(d,[["atredir","gopc"]]);n=s(d,[["atredir","gopc_err"]]);k=s(d,[["atredir","camp"]]);s("del",[["atredir","gopc"]]);s("del",[["atredir","gopc_err"]]);s("del",[["atredir","camp"]]);c=s(d,[["atsession","histo_camp"]]);m=s(d,[["atreman","camp"]]);e=s(d,[["atreman",
"date"]]);var t=w("getLocation",[]);f=w("getQueryStringValue",["xtor",t]);r=w("getQueryStringValue",["xtdt",t]);p=w("getQueryStringValue",["xts",t]);l=a.getContext("forcedCampaign");q=!!a.getConfig("redirect");if(u=f&&r&&p?!0:!1)t=(new Date).getTime()/6E4,z=!q&&p!==a.getConfig("site")||0>t-r||t-r>=a.getConfig("visitLifetime")?!0:!1;t=l||k||f;q&&t&&x("atredir",{path:"/",end:a.getConfig("redirectionLifetime")})&&(s(h,[["atredir","camp"],t]),s(h,[["atredir","gopc"],l?!1:k?g:u?!0:!1]),s(h,[["atredir",
"gopc_err"],l?!1:k?n:z?!0:!1]));!q&&m&&(A("xtor",m),t=(new Date).getTime()/36E5,t=Math.floor(t-e),A("roinbh",0<=t?t:0));q||(t=void 0,t=k?g?l||t:l||k:u?l||t:l||f||t,c&&c instanceof Array&&-1<c.indexOf(t)&&(t=void 0),t&&A("xto",t));if(!q&&!l){var v;k?n&&(v=k):z&&(v=f);v&&A("pgt",v)}q||!(v=k?l||k:l||f||void 0)||!l&&!k&&u&&z||!l&&k&&g&&n||((!c||c instanceof Array&&0>c.indexOf(v))&&x("atsession",{path:"/",session:60*a.getConfig("visitLifetime")})&&s(h,[["atsession","histo_camp"],c&&c.push(v)?c:[v]]),m&&
!b.lastPersistence||!x("atreman",{path:"/",session:86400*b.lifetime})||(s(h,[["atreman","camp"],v]),s(h,[["atreman","date"],(new Date).getTime()/36E5])));a.emit("Campaigns:"+y,{lvl:"INFO"})};(function(){var b=["Cookies","Utils"];if(-1===ATInternet.Utils.arrayIndexOf(a.getConfig("plgs"),"BackwardCompat"))a.plugins.waitForDependencies(b,function(){v("process2:done")});else a.onTrigger("BackCampaigns:process2:done",function(c,f){a.plugins.waitForDependencies(b,function(){v("process1:done")})},!0)})()};
window.ATInternet.Tracker.addPlugin("Campaigns");
}).call(window);;(function(){var dfltPluginCfg={"info":true};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.Clicks=function(a){var b=function(a){var b="";switch(a){case "exit":b="S";break;case "download":b="T";break;case "action":b="A";break;case "navigation":b="N"}return b},h=function(b){var d=b.name;a.exec("Utils","manageChapters",[b,"chapter",3],function(a){d=a+(d?d:"")});return d},d=function(d){var n={p:h(d),s2:d.level2||"",click:b(d.type)||""},k=a.getContext("page")||{};n.pclick=h(k);n.s2click=k.level2||"";d.customObject&&a.exec("Utils","customObjectToString",[d.customObject],
function(a){n.stc=a});a.sendHit(n,[["hitType",["click"]]])};a.click={};a.clickListener=this.clickListener={};a.click.send=this.send=function(b){var n=!0;a.plugins.exec("TechClicks","manageClick",[b.elem,b.event,b.callback],function(a){n=a});d(b);return n};a.clickListener.send=this.clickListener.send=function(b){if(b.elem){var n;a.plugins.exec("TechClicks","isFormSubmit",[b.elem],function(a){n=a?"submit":"click"});ATInternet.Utils.addEvtListener(b.elem,n,function(k){a.plugins.exec("TechClicks","manageClick",
[b.elem,k,b.callback]);d(b)})}};a.click.set=this.set=function(d){a.dispatchSubscribe("click");a.setContext("click",{name:h(d),level2:d.level2||"",customObject:d.customObject});a.setParam("click",b(d.type)||"",{hitType:["click"]})};a.click.onDispatch=this.onDispatch=function(){var b={hitType:["click"]};a.setParam("p",a.getContext("click").name,b);a.setParam("s2",a.getContext("click").level2,b);var d=a.getContext("click").customObject;d&&a.setParam("stc",d,{hitType:["click"],encode:!0});d=a.getContext("page")||
{};a.setParam("pclick",h(d),b);a.setParam("s2click",d.level2||"",b);a.sendHit(null,[["hitType",["click"]]]);a.setContext("click",void 0)}};window.ATInternet.Tracker.addPlugin("Clicks");
}).call(window);;(function(){var dfltPluginCfg={"clientSideMode":"required","userIdCookieDuration":397,"userIdExpirationMode":"fixed","optOut":"OPT-OUT","userIdCookieName":"atuserid","optOutCookieName":"atoptedout","info":true};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.ClientSideUserId=function(a){var b={},h=void 0,d=null,g=-1,n=!1;a.configPlugin("ClientSideUserId",dfltPluginCfg||{},function(a){b=a});var k=function(){h=a.getContext("userIdentifier");a.exec("Cookies","get",["atuserid"],function(a){d=a})},c=function(b,c,f){a.setParam("idclient",b,{permanent:!0,hitType:["all"]});m(f,b,c)},m=function(c,f,q){if("relative"===b.userIdExpirationMode||"fixed"===b.userIdExpirationMode&&null===d||q){var e=new Date;e.setTime(e.getTime()+864E5*
b.userIdCookieDuration);a.exec("Cookies","set",[c,f,{end:e,path:"/"}]);a.exec("Cookies","get",[c,!0],function(b){q||f===b||a.setParam("idclient",f+"-NO",{permanent:!0,hitType:["all"]})})}},e=function(){var c=!1,f=null,q=ATInternet.Utils.optedOut;!1===q&&(a.exec("Cookies","set",["atoptedout",null,{path:"/"}]),a.getParam("idclient")===b.optOut&&a.delParam("idclient"));a.exec("Cookies","get",["atoptedout",!0],function(a){f=a});if(!0===q||f===b.optOut)c=!0;c&&(ATInternet.Utils.optedOut=!0);return c},
f=function(a){a&&(a=a.detail)&&"clientsideuserid"===a.name&&a.id===g&&r()},r=function(){k();var f,l=!1;if("required"===b.clientSideMode){if(f=navigator.userAgent,/Safari/.test(f)&&!/Chrome/.test(f)||/iPhone|iPod|iPad/.test(f))l=!0}else"always"===b.clientSideMode&&(l=!0);f=l;l="undefined"!==typeof h;n=e();if(f||l||n){var q="";f=!1;var u=b.userIdCookieName;n?(q=b.optOut,f=!0,u=b.optOutCookieName):l?(q=h,f=!0):q=null!==d?d:ATInternet.Utils.uuid().v4();c(q,f,u)}a.emit("ClientSideUserId:Ready",{lvl:"INFO",
details:{clientSideMode:b.clientSideMode,userIdCookieDuration:b.userIdCookieDuration,userIdExpirationMode:b.userIdExpirationMode,userIdFromContext:h,userIdFromCookie:d,userId:q}})};(function(){a.plugins.waitForDependencies(["Cookies"],function(){var a=ATInternet.Utils.uuid();g=parseInt(a.num(8));ATInternet.Utils.removeOptOutEvent(f);ATInternet.Utils.addOptOutEvent(f,g);r()})})();a.clientSideUserId={};a.clientSideUserId.set=function(a){var f=b.userIdCookieName;n&&(a=b.optOut,f=b.optOutCookieName);
c(a,!0,f)}};window.ATInternet.Tracker.addPlugin("ClientSideUserId");
}).call(window);;(function(){var dfltPluginCfg={"domainAttribution":true,"info":true};var dfltGlobalCfg={"redirectionLifetime":30};window.ATInternet.Tracker.Plugins.ContextVariables=function(a){var b="",h=null,d,g="",n="",k={};a.configPlugin("ContextVariables",dfltPluginCfg||{},function(a){k=a});a.setConfig("redirectionLifetime",dfltGlobalCfg.redirectionLifetime,!0);var c=function(b,c,f){var d=null;a.plugins.exec(b,c,f,function(a){d=a});return d},m=function(a,b){return c("Utils",a,b)},e=function(b,c){var f=null;a.plugins.exec("Cookies",b,c,function(a){f=a});return f},f=function(){a.setParam("hl",function(){var a=new Date;return a.getHours()+
"x"+a.getMinutes()+"x"+a.getSeconds()},{permanent:!0,hitType:["all"]})},r=function(a){var c="",c=d?d:"acc_dir"===b?"":null!=b?b:"acc_dir"===h?"":h?h:a.referrer;return c.replace(/[<>]/g,"").substring(0,1600).replace(/&/g,"$")};a.plugins.waitForDependencies(["Cookies","Utils"],function(){g="set"+(k.domainAttribution?"":"Private");n="get"+(k.domainAttribution?"":"Private");var c=m("getLocation",[]);b=m("getQueryStringValue",["xtref",c]);void 0===b&&(b="");d=a.getContext("forcedReferer");if(a.getConfig("redirect")){var c=
m("getDocumentLevel",[]),c=d?d:null!=b?b:c.referrer||"acc_dir",l;if(l=c){l={path:"/",end:a.getConfig("redirectionLifetime")};var q=e(n,["atredir"]);null!==q?l="object"===typeof q&&!(q instanceof Array):(e(g,["atredir",{},l]),l=!0)}l&&e(g,[["atredir","ref"],c])}else{h=e(n,[["atredir","ref"]]);e("del",[["atredir","ref"]]);a.setParam("vtag",a.version,{permanent:!0,hitType:["all"]});a.setParam("ptag","js",{permanent:!0,hitType:["all"]});c="";try{c+=window.screen.width+"x"+window.screen.height+"x"+window.screen.pixelDepth+
"x"+window.screen.colorDepth}catch(u){}a.setParam("r",c,{permanent:!0,hitType:["all"]});c="";window.innerWidth?c+=window.innerWidth+"x"+window.innerHeight:document.body&&document.body.offsetWidth&&(c+=document.body.offsetWidth+"x"+document.body.offsetHeight);a.setParam("re",c,{permanent:!0,hitType:["all"]});f();a.setParam("lng",navigator.language||navigator.userLanguage,{permanent:!0,hitType:["all"]});c=ATInternet.Utils.uuid().num(13);a.setParam("idp",c,{permanent:!0,hitType:["page","clickzone"]});
a.setParam("jv",navigator.javaEnabled()?"1":"0",{hitType:["page"]});c=m("getDocumentLevel",[]);a.setParam("ref",r(c),{permanent:!0,last:!0,hitType:["page"]})}a.emit("ContextVariables:Ready",{lvl:"INFO"})})};window.ATInternet.Tracker.addPlugin("ContextVariables");
}).call(window);;(function(){var dfltPluginCfg={"info":false};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.Cookies=function(a){var b={},h={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(a){var b="",c,f,d,e,p,k,m=0;for(a=h._utf8_encode(a);m<a.length;)c=a.charCodeAt(m++),f=a.charCodeAt(m++),d=a.charCodeAt(m++),e=c>>2,c=(c&3)<<4|f>>4,p=(f&15)<<2|d>>6,k=d&63,isNaN(f)?p=k=64:isNaN(d)&&(k=64),b=b+this._keyStr.charAt(e)+this._keyStr.charAt(c)+this._keyStr.charAt(p)+this._keyStr.charAt(k);return b},decode:function(a){var b="",c,f,d,
e,p,k=0;for(a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");k<a.length;)c=this._keyStr.indexOf(a.charAt(k++)),f=this._keyStr.indexOf(a.charAt(k++)),e=this._keyStr.indexOf(a.charAt(k++)),p=this._keyStr.indexOf(a.charAt(k++)),c=c<<2|f>>4,f=(f&15)<<4|e>>2,d=(e&3)<<6|p,b+=String.fromCharCode(c),64!=e&&(b+=String.fromCharCode(f)),64!=p&&(b+=String.fromCharCode(d));return b=h._utf8_decode(b)},_utf8_encode:function(a){a=a.replace(/\r\n/g,"\n");for(var b="",c=0;c<a.length;c++){var f=a.charCodeAt(c);128>f?b+=String.fromCharCode(f):
(127<f&&2048>f?b+=String.fromCharCode(f>>6|192):(b+=String.fromCharCode(f>>12|224),b+=String.fromCharCode(f>>6&63|128)),b+=String.fromCharCode(f&63|128))}return b},_utf8_decode:function(a){for(var b="",c=0,f,d,e;c<a.length;)f=a.charCodeAt(c),128>f?(b+=String.fromCharCode(f),c++):191<f&&224>f?(d=a.charCodeAt(c+1),b+=String.fromCharCode((f&31)<<6|d&63),c+=2):(d=a.charCodeAt(c+1),e=a.charCodeAt(c+2),b+=String.fromCharCode((f&15)<<12|(d&63)<<6|e&63),c+=3);return b}},d=this.getCookie=function(b){return!a.getConfig("disableCookie")&&
b&&"string"===typeof b&&(b=RegExp("(?:^| )"+b+"=([^;]+)").exec(document.cookie)||null)?(b=b[1],b=a.getConfig("base64Storage")?h.decode(b):decodeURIComponent(b),b):null},g=this.setCookie=function(b,c,f){if(!a.getConfig("disableCookie")&&b&&"string"===typeof b&&"string"===typeof c){var d=a.getConfig("cookieDomain");b+="=";c=a.getConfig("base64Storage")?h.encode(c):encodeURIComponent(c);c=b+c;b=!1;if(f){b=f.secure;var e=f.end,p=f.domain;f=f.path;c+=e?"function"===typeof e.toGMTString?";expires="+e.toGMTString():
"number"===typeof e?";max-age="+e.toString():"":"";c=c+(d||p?";domain="+(p?p:d):"")+(f&&"string"===typeof f?";path="+f:"")}d=a.getConfig("cookieSecure")||b;c+=d&&"boolean"===typeof d?";secure":"";document.cookie=c;return!0}return null},n=function(a){var b=null;(a=d(a))&&(b=ATInternet.Utils.jsonParse(a));return b},k=function(a){return g(a.name,ATInternet.Utils.jsonSerialize(a),a.options)?a:null},c=function(a,c,f){var d=null;if(!f&&b[a])d=b[a];else if(d=n(a))d.options.session&&k(d),b[a]=d;return d?
c?(a=null,!d||"object"!==typeof d.val||d.val instanceof Array||void 0===d.val[c]||(a=d.val[c]),a):d.val:null},m=function(a,c,f,d){var e=null;if(c){if(e=n(a))d=e,!d||"object"!==typeof d.val||d.val instanceof Array?e=null:(d.val[c]=f,e=d),e&&(e=k(e))}else c=d=d||{},d={},d.name=a,d.val=f,c.session&&"number"===typeof c.session&&(c.end=c.session),d.options=c,e=k(d);e&&(b[a]=e);return e?e.val:null},e=function(a,c){c?m(a,c,void 0):(b[a]=void 0,g(a,"",{end:0}))},f=this.get=function(a,b){b=b||!1;return a instanceof
Array&&2===a.length?c(a[0],a[1],b):c(a,void 0,b)};this.getPrivate=function(b,c){c=c||!1;b instanceof Array?b[0]+=a.getConfig("site"):b+=a.getConfig("site");return f(b,c)};var r=this.set=function(a,b,c){return a instanceof Array?m(a[0],a[1],b):m(a,null,b,c)};this.setPrivate=function(b,c,f){b instanceof Array?b[0]+=a.getConfig("site"):b+=a.getConfig("site");return r(b,c,f)};var p=this.del=function(a){return a instanceof Array?e(a[0],a[1]):e(a)};this.delPrivate=function(b){b instanceof Array?b[0]+=a.getConfig("site"):
b+=a.getConfig("site");return p(b)};this.cacheInvalidation=function(){b={}}};window.ATInternet.Tracker.addPlugin("Cookies");
}).call(window);;(function(){var dfltPluginCfg={"lifetime":182,"domainAttribution":true,"info":true};var dfltGlobalCfg={"redirectionLifetime":30};window.ATInternet.Tracker.Plugins.IdentifiedVisitor=function(a){var b=null,h=null,d=null,g=null,n="",k="",c=null,m=null,e="",f="",r={};a.configPlugin("IdentifiedVisitor",dfltPluginCfg||{},function(a){r=a});a.setConfig("redirectionLifetime",dfltGlobalCfg.redirectionLifetime,!0);var p=function(b,c,f){var d=null;a.plugins.exec(b,c,f,function(a){d=a});return d},l=function(a,b){return p("Utils",a,b)},q=function(b,c){var f=null;a.plugins.exec("Cookies",b,c,function(a){f=a});return f},u=function(a,b){var c=
q(f,[a]);if(null!==c)return"object"===typeof c&&!(c instanceof Array);q(e,[a,{},b]);return!0},z=function(){var f=function(a,b){/-/.test(b)?(a.category=b.split("-")[0],a.id=b.split("-")[1]):a.id=b},e={category:"",id:""};f(e,k||m);var q={category:"",id:""};f(q,n||c);q.id?(q.category&&s("ac",q.category),s("at",q.id)):b&&a.setParam("at",b,{hitType:["all"],permanent:!0});e.id?(e.category&&s("ac",e.category),s("an",e.id)):h&&a.setParam("anc",d+"-"+h,{hitType:["all"],permanent:!0})},y=function(a,b){u("atidvisitor",
{path:"/",session:86400*r.lifetime})&&q(e,[["atidvisitor",a],b])},s=function(b,c){a.setParam(b,c,{hitType:["all"],permanent:!0});y(b,c)};a.plugins.waitForDependencies(["Cookies","Utils"],function(){e="set"+(r.domainAttribution?"":"Private");f="get"+(r.domainAttribution?"":"Private");var p=l("getLocation",[]);n=l("getQueryStringValue",["xtat",p]);k=l("getQueryStringValue",["xtan",p]);a.getConfig("redirect")?(n||k)&&u("atredir",{path:"/",end:a.getConfig("redirectionLifetime")})&&(k&&q(e,[["atredir",
"an"],k]),n&&q(e,[["atredir","at"],n])):(c=q(f,[["atredir","at"]]),m=q(f,[["atredir","an"]]),q("del",[["atredir","at"]]),q("del",[["atredir","an"]]),b=q(f,[["atidvisitor","at"]]),h=q(f,[["atidvisitor","an"]]),d=q(f,[["atidvisitor","ac"]]),g=q(f,[["atidvisitor","vrn"]]),z(),p="-"+a.getConfig("site")+"-",RegExp(p).test(g)||(g=(g||"")+p,y("vrn",g),p=a.getContext("page")||{},p.vrn=1,a.setContext("page",p)));a.emit("IdentifiedVisitor:Ready",{lvl:"INFO",details:{cookieRedirectTextual:c,cookieRedirectNumeric:m,
cookieTextual:b,cookieNumeric:h,cookieCategory:d,cookieVrn:g}})});a.identifiedVisitor={};a.identifiedVisitor.set=this.set=function(a){var b=a.id;a=a.category;"number"===typeof b?s("an",b.toString()):s("at",b);"undefined"!==typeof a&&s("ac",a)};a.identifiedVisitor.unset=this.unset=function(){for(var b=["an","at","ac"],c=0;c<b.length;c++)a.exec("Cookies","set",[["atidvisitor",b[c]],void 0]),a.delParam(b[c]);a.delParam("anc")}};window.ATInternet.Tracker.addPlugin("IdentifiedVisitor");
}).call(window);;(function(){var dfltPluginCfg={"urlKeyword":"","urlResultPageNumber":"","urlResultPosition":"","info":true};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.InternalSearch=function(a){var b={};a.configPlugin("InternalSearch",dfltPluginCfg||{},function(a){b=a});var h=function(b){var g={np:"undefined"!==typeof b.resultPageNumber?b.resultPageNumber:"1",click:"IS"};b.hasOwnProperty("keyword")&&(g.mc=b.keyword);b.hasOwnProperty("resultPosition")&&(g.mcrg=b.resultPosition);a.sendHit(g,[["hitType",["InternalSearch"]]])};a.internalSearch={};a.internalSearch.set=this.set=function(b){var g={},h=g;b.hasOwnProperty("keyword")&&(h.keyword=
b.keyword);h=g;b.hasOwnProperty("resultPageNumber")&&(h.resultPageNumber=b.resultPageNumber);b=a.getContext("InternalSearch")||{};g=ATInternet.Utils.completeFstLevelObj(g,b);"undefined"===typeof g.resultPageNumber&&(g.resultPageNumber="1");a.setContext("InternalSearch",g)};a.internalSearch.send=this.send=function(b){var g=!0;a.plugins.exec("TechClicks","manageClick",[b.elem,b.event,b.callback],function(a){g=a});h(b);return g};a.plugins.waitForDependencies(["Utils"],function(){var d;if(b.urlKeyword){var g=
document.location.href;d={};a.plugins.exec("Utils","getQueryStringValue",[b.urlKeyword,g],function(h){h&&(d.keyword=h);b.urlResultPageNumber&&a.plugins.exec("Utils","getQueryStringValue",[b.urlResultPageNumber,g],function(a){d.resultPageNumber=a||"1"})})}d&&a.setContext("InternalSearch",d);a.emit("InternalSearch:Ready",{lvl:"INFO",details:{config:{urlKeyword:b.urlKeyword,urlResultPageNumber:b.urlResultPageNumber},url:g,data:d}})})};window.ATInternet.Tracker.addPlugin("InternalSearch");
}).call(window);;(function(){var dfltPluginCfg={"info":true};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.OnSiteAds=function(a){var b="",h=function(b){var c=b.name;a.exec("Utils","manageChapters",[b,"chapter",3],function(a){c=a+(c?c:"")});return c},d=function(a,b){return a[b]?a[b]:""},g=function(a,b){var c=d(a,b);if(c){var e=d(a,"prefix");if(c.campaignId){var e=e||"PUB",q=d(c,"campaignId"),g=d(c,"creation"),k=d(c,"variant"),m=d(c,"format"),h=d(c,"generalPlacement"),n=d(c,"detailedPlacement"),x=d(c,"advertiserId"),c=d(c,"url");return e+"-"+q+"-"+g+"-"+k+"-"+m+"-"+h+"-"+
n+"-"+x+"-"+c}if(c.adId)return e=e||"INT",q=d(c,"adId"),g=d(c,"format"),c=d(c,"productId"),e+"-"+q+"-"+g+"||"+c}},n=function(b){var c=a.getContext("page")||{};a.sendHit({atc:g(b,"click"),type:"AT",patc:h(c),s2atc:c.level2||"",stc:b.customObject||""},[["hitType",["onSiteAdsClick"]]])},k=function(b){a.sendHit({ati:g(b,"impression"),type:"AT",stc:b.customObject||""},[["hitType",["onSiteAdsImpression"]]])},c=function(b,c){var d=a.buffer.get("ati",!0)||{};d.value="string"===typeof d.value?[d.value]:d.value||
[];d.options=d.options||{hitType:[c,"page"]};d.value.push(b);a.buffer.set("ati",d.value,d.options)},m=function(b,c){b.click?a.setParam("atc",g(b,"click"),{hitType:[c,"page"]}):b.impression&&a.setParam("ati",g(b,"impression"),{hitType:[c,"page"]});if(b.customObject){a.setContext("onsiteads",{customObject:b.customObject});var d=a.getContext("page")||{};d.customObject=ATInternet.Utils.completeFstLevelObj(d.customObject,b.customObject,!1);a.setContext("page",d)}a.dispatchSubscribe("onSiteAds")};a.selfPromotion=
this.selfPromotion={};a.publisher=this.publisher={};a.publisher.set=this.publisher.set=function(a){m(a,"publisher")};a.selfPromotion.set=this.selfPromotion.set=function(a){m(a,"selfPromotion")};a.publisher.add=this.publisher.add=function(b){c(g(b,"impression"),"publisher");a.dispatchSubscribe("onSiteAds")};a.selfPromotion.add=this.selfPromotion.add=function(b){c(g(b,"impression"),"selfPromotion");a.dispatchSubscribe("onSiteAds")};var e=this.advertEvent=function(b){var c=!0;a.exec("TechClicks","manageClick",
[b.elem,b.event,b.callback],function(a){c=a});b.click?n(b):b.impression&&k(b);return c};a.publisher.send=this.publisher.send=function(a){return e(a)};a.selfPromotion.send=this.selfPromotion.send=function(a){return e(a)};a.onSiteAds={};a.onSiteAds.onDispatch=this.onDispatch=function(){if(!a.dispatchSubscribed("page")){var b=a.getContext("page")||{};a.setParam("type","AT",{hitType:["publisher","selfPromotion"]});a.getParam("atc")&&(a.setParam("patc",h(b),{hitType:["publisher","selfPromotion"]}),a.setParam("s2atc",
b.level2||"",{hitType:["publisher","selfPromotion"]}));(b=a.getContext("onsiteads"))&&b.customObject&&a.setParam("stc",b.customObject,{encode:!0,hitType:["publisher","selfPromotion"]});a.sendHit(null,[["hitType",["publisher","selfPromotion"]]])}};a.plugins.waitForDependencies(["Utils","TechClicks"],function(){b=document.location.href;a.plugins.exec("Utils","getQueryStringValue",["xtatc",b],function(b){b&&a.setParam("atc",b,{hitType:["publisher","selfPromotion","page"]})});a.emit("OnSiteAds:Ready",
{lvl:"INFO",details:{href:b}})})};window.ATInternet.Tracker.addPlugin("OnSiteAds");
}).call(window);;(function(){var dfltPluginCfg={"info":true};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.Page=function(a){var b=["pageId","chapterLabel","update"],h=["pid","pchap","pidt"],d=["page","site"],g=["f","x"],n=function(b){var c=b.name;a.exec("Utils","manageChapters",[b,"chapter",3],function(a){c=a+(c?c:"")});return c},k=function(a,b,c){b?a=b:a||"undefined"===typeof c||(a=c);return a},c=function(a,b,c){b.hasOwnProperty(c)&&(a[c]=k(a[c],b[c]))},m=function(b){if(!ATInternet.Utils.isPreview()||a.getConfig("preview"))ATInternet.Utils.isPrerender(function(a){b(a)})||
b()},e=function(b,c,f){if(c)for(var e=0;e<d.length;e++)if(c.hasOwnProperty(d[e])&&c[d[e]])for(var l in c[d[e]])c[d[e]].hasOwnProperty(l)&&(f?b[g[e]+l]=c[d[e]][l]:a.setParam(g[e]+l,c[d[e]][l]))},f=function(c,f,d){if(f){a.exec("Utils","manageChapters",[f,"chapter",3],function(a){a&&(f.chapterLabel=a.replace(/::$/gi,""))});for(var e=0;e<h.length;e++)f.hasOwnProperty(b[e])&&(d?c[h[e]]=f[b[e]]:a.setParam(h[e],f[b[e]]))}},r=function(b,c,f){if(c&&c.keywords instanceof Array){var d=c.keywords.length;if(0<
d){for(var e="",g=0;g<d;g++)e+="["+c.keywords[g]+"]"+(g<d-1?"|":"");f?b.tag=e:a.setParam("tag",e)}}},p=function(b,c,f){if(c){var d,e=function(a){return a?a:"0"};d=""+(e(c.category1)+"-");d+=e(c.category2)+"-";d+=e(c.category3);f?b.ptype=d:a.setParam("ptype",d)}},l=function(b,c,f){if(c)for(var d in c)c.hasOwnProperty(d)&&"undefined"!==typeof c[d]&&(f?b[d]=c[d]:a.setParam(d,c[d]))};a.customVars=this.customVars={};a.customVars.set=this.customVars.set=function(b){var c=a.getContext("page")||{},f=c.customVars;
if(f){if(b)for(var d in b)b.hasOwnProperty(d)&&(f[d]=ATInternet.Utils.completeFstLevelObj(f[d],b[d],!0))}else f=b;c.customVars=f;a.setContext("page",c)};a.dynamicLabel=this.dynamicLabel={};a.dynamicLabel.set=this.dynamicLabel.set=function(b){var c=a.getContext("page")||{};c.dynamicLabel=ATInternet.Utils.completeFstLevelObj(c.dynamicLabel,b,!0);a.setContext("page",c)};a.tags=this.tags={};a.tags.set=this.tags.set=function(b){var c=a.getContext("page")||{};c.tags=ATInternet.Utils.completeFstLevelObj(c.tags,
b,!0);a.setContext("page",c)};a.customTreeStructure=this.customTreeStructure={};a.customTreeStructure.set=this.customTreeStructure.set=function(b){var c=a.getContext("page")||{};c.customTreeStructure=ATInternet.Utils.completeFstLevelObj(c.customTreeStructure,b,!0);a.setContext("page",c)};a.page={};a.page.reset=this.reset=function(){a.setContext("page",void 0)};a.page.set=this.set=function(b){a.dispatchSubscribe("page");var f=a.getContext("page")||{};f.name=k(f.name,b.name,"");f.level2=k(f.level2,
b.level2,"");c(f,b,"chapter1");c(f,b,"chapter2");c(f,b,"chapter3");f.customObject=ATInternet.Utils.completeFstLevelObj(f.customObject,b.customObject,!0);a.setContext("page",f)};a.page.send=this.send=function(b){var d={p:n(b),s2:b.level2||""},g=!0,h=b.customObject;if(h){var s=a.getParam("stc",!0);if(s&&s.options.permanent){var w=s?s.options.hitType:[],x=ATInternet.Utils.arrayIndexOf;if(-1!=x(w,"page")||-1!=x(w,"all"))h=ATInternet.Utils.completeFstLevelObj(s.value||{},h,!0)}a.exec("Utils","customObjectToString",
[h],function(a){d.stc=a})}h=a.getContext("page")||{};h.vrn&&(d.vrn=h.vrn,h.vrn=void 0,a.setContext("page",h));s=a.getContext("InternalSearch")||{};"undefined"!=typeof s.keyword&&(d.mc=ATInternet.Utils.cloneSimpleObject(s.keyword),"undefined"!=typeof s.resultPageNumber&&(d.np=ATInternet.Utils.cloneSimpleObject(s.resultPageNumber)),a.setContext("InternalSearch",void 0));ATInternet.Utils.isPreview()&&a.getConfig("preview")&&(d.pvw=1);e(d,b.customVars,!0);f(d,b.dynamicLabel,!0);r(d,b.tags,!0);p(d,b.customTreeStructure,
!0);s=a.getContext("campaigns")||{};l(d,s,!0);a.setContext("campaigns",void 0);a.exec("TechClicks","manageClick",[b.elem,b.event,b.callback],function(a){g=a});m(function(){a.sendHit(d)});h.name=k(h.name,b.name,"");h.level2=k(h.level2,b.level2,"");c(h,b,"chapter1");c(h,b,"chapter2");c(h,b,"chapter3");a.setContext("page",h);return g};a.page.onDispatch=this.onDispatch=function(){var b=a.getContext("page")||{},c=a.getContext("InternalSearch")||{};a.setParam("p",n(b));a.setParam("s2",b.level2||"");b.vrn&&
(a.setParam("vrn",b.vrn),b.vrn=void 0,a.setContext("page",b));"undefined"!=typeof c.keyword&&(a.setParam("mc",ATInternet.Utils.cloneSimpleObject(c.keyword)),"undefined"!=typeof c.resultPageNumber&&a.setParam("np",ATInternet.Utils.cloneSimpleObject(c.resultPageNumber)),a.setContext("InternalSearch",void 0));ATInternet.Utils.isPreview()&&a.getConfig("preview")&&a.setParam("pvw",1);e(null,b.customVars,!1);f(null,b.dynamicLabel,!1);r(null,b.tags,!1);p(null,b.customTreeStructure,!1);c=a.getContext("campaigns")||
{};l(null,c,!1);a.setContext("campaigns",void 0);var b=b.customObject,d=[["hitType",["page"]]];if(b)if(c=a.getParam("stc",!0)){var g=c.options.hitType||[],k=ATInternet.Utils.arrayIndexOf,k=-1!=k(g,"page")||-1!=k(g,"all"),g=c.options.permanent;k?(k=ATInternet.Utils.cloneSimpleObject(c),k.value=ATInternet.Utils.completeFstLevelObj(k.value||{},b,!0),a.setParam("stc",k.value,{encode:!0}),m(function(){a.sendHit(null,d)}),g&&a.setParam("stc",c.value,c.options)):(a.setParam("stc",b,{encode:!0}),m(function(){a.sendHit(null,
d)}),a.setParam("stc",c.value,c.options))}else a.setParam("stc",b,{encode:!0}),m(function(){a.sendHit(null,d)});else m(function(){a.sendHit(null,d)})}};window.ATInternet.Tracker.addPlugin("Page");
}).call(window);;(function(){var dfltPluginCfg={"info":true};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.RichMedia=function(a){var b=new function(){this._timeout={};this.setTimeout=function(b,c,d){this._timeout[b]=this._timeout[b]||{};window.clearTimeout(this._timeout[b][c]);this._timeout[b][c]=window.setTimeout(function(){a.richMedia.send({action:"refresh",playerId:b,mediaLabel:c})},1E3*d)};this.setTimeoutObject=function(b,c,d,e){this._timeout[b]=this._timeout[b]||{};if("undefined"===typeof this._timeout[b][c]){var g=[],h;for(h in d)d.hasOwnProperty(h)&&g.push({delay:k(h,
0),refresh:k(d[h],5)});g.sort(function(a,b){return a.delay<b.delay?-1:a.delay>b.delay?1:0});this._timeout[b][c]={arrObj:g,arrObjSave:ATInternet.Utils.cloneSimpleObject(g)}}d=this._timeout[b][c];if(0<d.arrObj.length&&(g=d.arrObj[0].delay,h=d.arrObj[0].refresh,"number"===typeof g&&"number"===typeof h&&0<h)){d[g]=d[g]||{};var m=void 0;"undefined"!==typeof d.arrObj[1]&&(m=d.arrObj[1].delay);var n=0;"undefined"===typeof m?n=1:"number"===typeof d[g].num?n="refresh"===e?Math.max(d[g].num-1,0):d[g].num:"number"===
typeof m&&(n=Math.floor(60*(m-g)/h)-1);d[g].num=n;window.clearTimeout(d[g].timeout);0<n?d[g].timeout=window.setTimeout(function(){a.richMedia.send({action:"refresh",playerId:b,mediaLabel:c})},1E3*h):(d[g].num=void 0,d[g].timeout=void 0,d.arrObj.splice(0,1),window.setTimeout(function(){a.richMedia.send({action:"refresh",playerId:b,mediaLabel:c})},1E3*h));this._timeout[b][c]=d}};this.clearTimeout=function(a,b,c){this._timeout[a]=this._timeout[a]||{};if("object"===typeof this._timeout[a][b]){for(var d in this._timeout[a][b])if(this._timeout[a][b].hasOwnProperty(d)){var e=
this._timeout[a][b][d].num;"undefined"!==typeof e&&0<e&&(window.clearTimeout(this._timeout[a][b][d].timeout),this._timeout[a][b][d].timeout=void 0)}c&&(this._timeout[a][b].arrObj=ATInternet.Utils.cloneSimpleObject(this._timeout[a][b].arrObjSave))}else window.clearTimeout(this._timeout[a][b])};this.removePlayer=function(b){for(var c in this._timeout[b])this._timeout[b].hasOwnProperty(c)&&(this.clearTimeout(b,c,!1),a.richMedia.send({action:"stop",playerId:b,mediaLabel:c}));this._timeout[b]={}};this.removeAll=
function(){for(var a in this._timeout)this._timeout.hasOwnProperty(a)&&this.removePlayer(a);this._timeout={}}},h=new function(){this._media=function(){this.type=void 0;this.plyr=0;this.clnk=this.s2=void 0;this.p="";this.m9=this.m6=this.m5=this.m1=this.rfsh=this.buf=this.a=void 0};this._mediaAll={};this.setMediaProperty=function(a,b,c,d){this._mediaAll[a]=this._mediaAll[a]||{};this._mediaAll[a][b]=this._mediaAll[a][b]||new this._media;this._mediaAll[a][b][c]=d};this.getMediaProperty=function(a,b,c){if(this._mediaAll[a]&&
this._mediaAll[a][b])return this._mediaAll[a][b][c]};this.removePlayer=function(a){this._mediaAll[a]={}};this.removeAll=function(){this._mediaAll={}}},d=function(b,c,d){var e=b[d]||"";a.exec("Utils","manageChapters",[b,c,3],function(a){e=a+e});return e},g=function(a,b,c,d){var e=a[b];"boolean"===typeof a[b]&&(e=a[b]?d:c);return e},n=function(a){var b=0;/^(\-|\+)?([0-9]+)$/.test(a)&&(b=Number(a));return b},k=function(a,b){var c=parseInt(a,10);return c?Math.max(c,b):0},c=function(a,b,c,d,e){b=h.getMediaProperty(b,
c,d);"undefined"!==typeof b&&(a[d]=e?encodeURIComponent(b):b)},m=function(a,b,c){"undefined"!==typeof c&&(a[b]=c)},e=function(a,b,c,d){"undefined"!==typeof d&&h.setMediaProperty(a,b,c,d)};a.richMedia={};a.richMedia.add=this.add=function(a){a=a||{};var b=n(a.playerId),c=d(a,"mediaTheme","mediaLabel"),k=g(a,"isEmbedded","int","ext");e(b,c,"plyr",b);e(b,c,"type",a.mediaType);e(b,c,"s2",a.mediaLevel2);e(b,c,"p",c);e(b,c,"clnk",a.linkedContent||a.previousMedia);e(b,c,"a",a.action);e(b,c,"rfsh",a.refreshDuration);
e(b,c,"m1",a.duration);e(b,c,"m5",k);e(b,c,"m6",a.broadcastMode);e(b,c,"m9",a.webdomain)};a.richMedia.remove=this.remove=function(a){b.removePlayer(a);h.removePlayer(a)};a.richMedia.removeAll=this.removeAll=function(){b.removeAll();h.removeAll()};a.richMedia.send=this.send=function(e){e=e||{};var r=n(e.playerId),p=d(e,"mediaTheme","mediaLabel"),l={};l.plyr=r;l.p=p;e.action&&(l.a=e.action);c(l,r,p,"type",!1);c(l,r,p,"s2",!1);c(l,r,p,"m1",!1);c(l,r,p,"m5",!1);c(l,r,p,"m6",!1);if("play"===l.a||"info"===
l.a){e=g(e,"isBuffering","0","1");m(l,"buf",e);e=a.getContext("page")||{};var q=d(e,"chapter","name")||void 0;m(l,"prich",q);m(l,"s2rich",e.level2||void 0);c(l,r,p,"clnk",!1);c(l,r,p,"m9",!0)}a.sendHit(l,[["hitType",["richmedia"]]]);"pause"===l.a?b.clearTimeout(r,p,!1):"stop"===l.a&&b.clearTimeout(r,p,!0);if("play"===l.a||"refresh"===l.a)e=h.getMediaProperty(r,p,"rfsh"),"object"===typeof e?b.setTimeoutObject(r,p,e,l.a):(l=k(e,5),0!==l&&b.setTimeout(r,p,l))}};window.ATInternet.Tracker.addPlugin("RichMedia");
}).call(window);;(function(){var dfltPluginCfg={"info":true};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.SalesTracker=function(a){var b=function(b,d,e){b.hasOwnProperty(e)&&(b=b[e],a.setParam(d,void 0===b?"":b+"",{hitType:["page"]}))},h=function(a){for(var b in a)if(a.hasOwnProperty(b))return!1;return!0},d=function(a){return"object"===typeof a&&!(a instanceof Array)},g=function(b){var d="";a.exec("Utils","manageChapters",[b,"category",6],function(a){a&&(d=a)});d+=b.productId;b=a.getContext("product")||{};b.viewedProducts?b.viewedProducts.push(d):b.viewedProducts=[d];
a.setContext("product",b)},n=0,k=function(b){var d=b.productId?b.productId:"",e=b.category?b.category+"::":"";a.exec("Utils","manageChapters",[b,"category",6],function(a){a&&(e=a)});return e+d};a.order=this.order={};a.cart=this.cart={};a.aisle=this.aisle={};a.salesTracker={};a.product=this.product={};a.order.set=this.order.set=function(c){var g=!1;if(d(c)&&!h(c)){g=!0;a.dispatchSubscribe("page");a.dispatchSubscribe("salesTracker");b(c,"cmd","orderId");b(c,"roimt","turnover");b(c,"st","status");"boolean"===
typeof c.newCustomer?a.setParam("newcus",c.newCustomer?"1":"0",{hitType:["page"]}):c.newCustomer&&"undefined"===typeof a.getParams("newcus")&&a.setParam("newcus","0",{hitType:["page"]});var e=c.amount;d(e)&&(b(e,"mtht","amountTaxFree"),b(e,"mtttc","amountTaxIncluded"),b(e,"tax","taxAmount"));e=c.delivery;d(e)&&(b(e,"fp","shippingFeesTaxIncluded"),b(e,"fpht","shippingFeesTaxFree"),b(e,"dl","deliveryMethod"));b(c,"mp","paymentMethod");e=c.discount;d(e)&&(b(e,"dsc","discountTaxIncluded"),b(e,"dscht",
"discountTaxFree"),b(e,"pcd","promotionalCode"));"boolean"===typeof c.confirmationRequired?a.setParam("tp",c.confirmationRequired?"pre1":"",{hitType:["page"]}):c.confirmationRequired&&"undefined"===typeof a.getParams("tp")&&a.setParam("tp","",{hitType:["page"]});c=c.orderCustomVariables;if(c instanceof Array)for(e=0;e<c.length;e++)b(c,"o"+(e+1),e)}return g};a.cart.set=this.cart.set=function(c){var g=!1;d(c)&&!h(c)&&(g=!0,a.dispatchSubscribe("page"),a.dispatchSubscribe("salesTracker"),b(c,"idcart",
"cartId"),"boolean"===typeof c.isBasketPage?"pre1"!==a.getParams("tp")&&a.setParam("tp",c.isBasketPage?"cart":"",{hitType:["page"]}):c.isBasketPage&&"undefined"===typeof a.getParams("tp")&&a.setParam("tp","",{hitType:["page"]}));return g};a.cart.add=this.cart.add=function(c){var g=!1;if(d(c)&&!h(c)&&(g=!0,c=c.product,d(c))){n++;var e=n,f=k(c);a.setParam("pdt"+e,f,{hitType:["page"]});b(c,"qte"+e,"quantity");b(c,"mt"+e,"unitPriceTaxIncluded");b(c,"mtht"+e,"unitPriceTaxFree");b(c,"dsc"+e,"discountTaxIncluded");
b(c,"dscht"+e,"discountTaxFree");b(c,"pcode"+e,"promotionalCode")}return g};a.aisle.set=this.aisle.set=function(b){var g=!1;if(d(b)&&!h(b)){g=!0;a.dispatchSubscribe("page");var e="";a.exec("Utils","manageChapters",[b,"level",6],function(a){e=a});e=e.replace(/::$/gi,"");a.setParam("aisl",e,{hitType:["page"]})}return g};a.product.add=this.product.add=function(b){var k=!1,e;if(e=d(b))if(e=!h(b)){a:{e=["productId"];for(var f=0;f<e.length;f++)if(void 0===b[e[f]]){e=!0;break a}e=!1}e=!e}e&&(k=!0,g(b),a.dispatchSubscribe("salesTracker"));
return k};a.salesTracker.onDispatch=this.onDispatch=function(){a.getParams("cmd");a.getParams("idcart")||"cart"!==a.getParams("tp")&&a.getParams("tp");var b=a.getContext("product");b&&b.viewedProducts&&0<b.viewedProducts.length&&(a.setParam("pdtl",b.viewedProducts.join("|"),{hitType:["product"]}),a.setParam("type","pdt",{hitType:["product"]}),a.sendHit(null,[["hitType",["product"]]]))}};window.ATInternet.Tracker.addPlugin("SalesTracker");
}).call(window);;(function(){var dfltPluginCfg={"clicksAutoManagementEnabled":true,"clicksAutoManagementTimeout":500,"info":false};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.TechClicks=function(a){var b,h;a.configPlugin("TechClicks",dfltPluginCfg||{},function(a){b=a.clicksAutoManagementEnabled;h=a.clicksAutoManagementTimeout});this.deactivateAutoManagement=function(){b=!1};var d=function(a){switch(a.target){case "_top":window.top.location.href=a.url;break;case "_parent":window.parent.location.href=a.url;break;default:window.location.href=a.url}},g=function(a){var b=a.timeout;a.mailto?setTimeout(function(){window.location.href=a.mailto},
b):a.form?setTimeout(function(){a.form.submit()},b):a.url&&setTimeout(function(){d({url:a.url,target:a.target})},b)},n=function(b){for(var c,k="_self",m=b.timeoutonly;b;){if(b.href&&0===b.href.indexOf("http")){c=b.href.split('"').join('\\"');k=b.target?b.target:k;break}b=b.parentNode}if(c){if(!m)a.onTrigger("Tracker:Hit:Sent:Ok",function(){d({url:c,target:k})});g({url:c,target:k,timeout:h})}},k=function(b){var c=b;for(b=c.timeoutonly;c&&"FORM"!==c.nodeName;)c=c.parentNode;if(c){if(!b)a.onTrigger("Tracker:Hit:Sent:Ok",
function(){c.submit()});g({form:c,timeout:h})}},c=function(b){var c=b;for(b=c.timeoutonly;c&&!(c.href&&0<=c.href.indexOf("mailto:"));)c=c.parentNode;if(c){if(!b)a.onTrigger("Tracker:Hit:Sent:Ok",function(){window.location.href=c.href});g({mailto:c.href,timeout:h})}},m=function(a){for(;a;){if(a.href){if(0<=a.href.indexOf("mailto:"))return"mailto";if(0===a.href.indexOf("http"))return"redirection"}else if("FORM"===a.nodeName)return"form";a=a.parentNode}return!1};this.manageClick=function(a,d,g){var h=
!0;if(b&&a){var l;a:{for(l=a;l;){if("function"===typeof l.getAttribute&&("_blank"===l.getAttribute("target")||"no"===l.getAttribute("data-atclickmanagement"))){l=!0;break a}l=l.parentNode}l=a;for(var q=window.location.href,u;l;){if((u=l.href)&&0<u.indexOf("#")&&q.substring(0,0<q.indexOf("#")?q.indexOf("#"):q.length)===u.substring(0,u.indexOf("#"))){l=!0;break a}l=l.parentNode}l=!1}q=m(a);if(!l&&q)switch(q){case "mailto":c(a);h=!1;break;case "form":k(a);h=!1;break;case "redirection":n(a),h=!1}}d&&
(a=d.defaultPrevented,"function"===typeof d.isDefaultPrevented&&(a=d.isDefaultPrevented()),a||d.preventDefault&&d.preventDefault());g&&g();return h}};window.ATInternet.Tracker.addPlugin("TechClicks");
}).call(window);;(function(){var dfltPluginCfg={"info":false};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.Utils=function(a){var b=this,h={};b.getQueryStringValue=function(a,b){var d=window.ATInternet.Utils.hashcode(b).toString();if(!h[d]){h[d]={};var c=RegExp("[&#?]{1}([^&=#?]*)=([^&#]*)?","g"),m=c.exec(b);if(null!==m)for(;null!==m;)h[d][m[1]]=m[2],m=c.exec(b)}return h[d].hasOwnProperty(a)?h[d][a]:null};b.customObjectToString=function(a){return encodeURIComponent(window.ATInternet.Utils.jsonSerialize(a))};b.manageChapters=function(b,d,h){var c=a.getConfig("ignoreEmptyChapterValue"),
m="";if(b){h=parseInt(h,10);for(var e=1;e<h+1;e++)var f=b[d+e]||"",m=c?m+(f?f+"::":""):m+(b.hasOwnProperty(d+e)?f+"::":"")}return m};b.getDocumentLevel=function(){var b=a.getConfig("documentLevel");if(0>b.indexOf("."))return window[b]||document;b=b.split(".");return window[b[0]][b[1]]||document};b.getLocation=function(){return b.getDocumentLevel().location.href};a.dispatchIndex={};a.dispatchStack=[];a.dispatchEventFor={};var d=0;a.dispatchSubscribe=function(b){return a.dispatchIndex[b]?!1:(a.dispatchStack.push(b),
a.dispatchIndex[b]=!0)};a.dispatchSubscribed=function(b){return!0===a.dispatchIndex[b]};a.addSpecificDispatchEventFor=function(b){return a.dispatchEventFor[b]?!1:(a.dispatchEventFor[b]=!0,d++,!0)};a.processSpecificDispatchEventFor=function(b){a.dispatchEventFor[b]&&(a.dispatchEventFor[b]=!1,d--,0===d&&(a.dispatchEventFor={},a.emit("Tracker:Plugin:SpecificEvent:Exec:Complete",{lvl:"INFO"})))};a.dispatch=function(){var b=function(){for(;0<a.dispatchStack.length;){var b=a.dispatchStack.pop();a[b].onDispatch()}a.dispatchIndex=
{};a.delContext(void 0,"customObject")},h=function(){if(a.plugins.isExecWaitingLazyloading())a.onTrigger("Tracker:Plugin:Lazyload:Exec:Complete",function(){b()},!0);else b()};if(0===d)h();else a.onTrigger("Tracker:Plugin:SpecificEvent:Exec:Complete",function(){h()},!0)};a.dispatchRedirect=function(b){var d=!0;b&&b.elem&&(b.elem.timeoutonly=!0,a.plugins.exec("TechClicks","manageClick",[b.elem,b.event,b.callback],function(a){d=a}));a.dispatch();return d}};window.ATInternet.Tracker.addPlugin("Utils");
}).call(window);
if(typeof window.ATInternet.onTrackerLoad==='function'){window.ATInternet.onTrackerLoad();}